### ISSUE TITLE
[BUG]f2更新到0.0.1.6后单个视频下载还是返回空

### ISSUE THREAD

**Issue by sakuraIsNow** [Johnserf-Seed/f2#111]
![image](https://github.com/Johnserf-Seed/f2/assets/168175553/b8ddb37a-b411-48fd-8131-60a871c9dd9e)
更新到0.0.1.6后单个视频下载还是返回空

**Comment by Johnserf-Seed** [comment]
ua配置用
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0

**Comment by sakuraIsNow** [comment]
> ua配置用 `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0`

感谢大佬回复！！
