### ISSUE TITLE
新版本 对接F2 项目了, 原来有的关键词搜索接口请问还有吗

### ISSUE THREAD

**Issue by scccy** [Johnserf-Seed/f2#113]
- [ ] ~~*在提问时请注意不要包含个人敏感信息*~~
- [ ] 我明白我的提问可能不会得到明确回复或解决。

**问题描述**
简要描述你想要获取支持或询问的内容。

**其他细节**
提供任何相关的细节或背景信息，例如你要询问的函数或与项目相关的具体内容。

**截图/代码示例**
如果有必要，可以提供截图或代码示例以更好地说明问题或询问的内容。

**期望的支持**
简要说明你期望从社区或项目维护者那里得到的支持或回答。

**其他**
如果有其他需要补充的内容，请在此处添加。

**Comment by scccy** [comment]
发错项目了...

**Comment by Johnserf-Seed** [comment]
暂时没有添加抖音的搜索接口的想法，可以参考代码自行实现一下
