### ISSUE TITLE
tiktok下载出错

### ISSUE THREAD

**Issue by wellchang** [Johnserf-Seed/f2#120]
![WeChat截图_20240703162249](https://github.com/Johnserf-Seed/f2/assets/29394679/8245cc04-2654-4180-a208-3f89c5c30806)
大佬 请教下tiktok 下载出现这个怎么解决？

**Comment by Johnserf-Seed** [comment]
贴完整的日志，这个报错看不出问题，如果`url`是带参数的可能需要用双引号包裹
