### ISSUE TITLE
[BUG]有些下载仍然报错 TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by navyNIE** [Johnserf-Seed/f2#124]
更新了最新版0.0.1.6，有些博主的下载可以正常完成，但有些仍然报错。
 if len(aweme) == 1
TypeError: object of type 'NoneType' has no len()
跟以前的报错一样

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/Johnserf-Seed/f2/assets/40727745/7a75ac64-d607-4978-ab22-ee863b3705a5)
