### ISSUE TITLE
[QUESTION]推特无法创建初始配置

### ISSUE THREAD

**Issue by RallyQ** [Johnserf-Seed/f2#145]
抖音微博能正常下载。
第一次想用推特下载，用命令 f2 x --init-config x.yaml 创建初始配置，提示
```
INFO     应用：twitter
INFO     twitter 应用配置未找到
```

推特下载功能失效了么？

**Comment by RallyQ** [comment]
> > 抖音微博能正常下载。 第一次想用推特下载，用命令 f2 x --init-config x.yaml 创建初始配置，提示
> > ```
> > INFO     应用：twitter
> > INFO     twitter 应用配置未找到
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 推特下载功能失效了么？
> 
> 没有失效，`defaults.yaml`对`twitter`的命名使用了简写，你把`x`改成`twitter`就可以创建了，但是目前`twitter`的小bug比较多


改了，配置创建了，导入了火狐中能正常访问的推特帐号cookie
也配置了正常使用的代理，但下载时提示
```
INFO     开始爬取推文：xxx
ERROR    HTTP状态错误：Client error '403 Forbidden' for url
```

若使用错误的代理地址，会提示
`ERROR    网络连接失败，请检查当前网络环境。`

**Comment by Johnserf-Seed** [comment]
X-Csrf-Token配置了吗，在twitter的xhr请求中可以找到，配置到conf.yaml里

**Comment by RallyQ** [comment]
> `X-Csrf-Token`配置了吗，在`twitter`的`xhr`请求中可以找到，配置到`conf.yaml`里

加上这个，能下载了，感谢及时回复！

**Comment by RallyQ** [comment]
tiktok也无法创建新配置，出现一堆错误提示
f2 tiktok --init-config tiktok.yaml

**Comment by RallyQ** [comment]
解决了，是网络问题
