### ISSUE TITLE
[BUG]AttributeError: 'APINotFoundError' object has no attribute 'format'

### ISSUE THREAD

**Issue by foxmail2048** [Johnserf-Seed/f2#150]
import asyncio
from f2.apps.tiktok.handler import TiktokHandler
from f2.apps.tiktok.utils import SecUserIdFetcher

kwargs = {
    "headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0",
        "Referer": "https://www.tiktok.com/",
    },
    "proxies": {"http://": None, "https://": None},
    "timeout": 10,
    "cookie": "YOUR_COOKIE_HERE",
}

async def main():
    secUid = await SecUserIdFetcher.get_secuid("https://www.tiktok.com/@vantoan___")

    async for aweme_data_list in TiktokHandler(kwargs).fetch_user_post_videos(
        secUid, 0, 30, None
    ):
        print("=================_to_raw================")
        print(aweme_data_list._to_raw())
        # print("=================_to_dict===============")
        # print(aweme_data_list._to_dict())
        # print("=================_to_list===============")
        # print(aweme_data_list._to_list())

if __name__ == "__main__":
    asyncio.run(main())
    
    
    
    报错如下：
    ERROR    请前往QA文档 https://johnserf-seed.github.io/f2/question-answer/qa.html 查看相关帮助                                                                                  
Traceback (most recent call last):
  File "/home/www/web/tk/python/main.py", line 32, in <module>
    asyncio.run(main())
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.pyenv/versions/3.9.0/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/www/web/tk/python/main.py", line 18, in main
    secUid = await SecUserIdFetcher.get_secuid("https://www.tiktok.com/@vantoan___")
  File "/root/.pyenv/versions/env3.9.0/lib/python3.9/site-packages/f2/apps/tiktok/utils.py", line 566, in get_secuid
    raise APINotFoundError(
AttributeError: 'APINotFoundError' object has no attribute 'format'

**Comment by Johnserf-Seed** [comment]
需要配置参数才可以请求，不然是空响应
