### ISSUE TITLE
没有符合条件的作品

### ISSUE THREAD

**Issue by QiQi777iii** [Johnserf-Seed/f2#156]
**问题描述**
正确填写了cookie 无法找到作品

**其他细节**
提供任何相关的细节或背景信息，例如你要询问的函数或与项目相关的具体内容。
Python 3.12.4
**截图/代码示例**
![2024-07-26_21-08](https://github.com/user-attachments/assets/fca1427e-6b67-4d57-b24c-6a38b5bd593e)

**期望的支持**
求如何解决
**其他**
如果有其他需要补充的内容，请在此处添加。

**Comment by Johnserf-Seed** [comment]
https://johnserf-seed.github.io/f2/question-answer/qa.html#warning-%E6%B2%A1%E6%9C%89%E6%89%BE%E5%88%B0%E7%AC%A6%E5%90%88%E6%9D%A1%E4%BB%B6%E7%9A%84%E4%BD%9C%E5%93%81
