### ISSUE TITLE
[QUESTION]url 403

### ISSUE THREAD

**Issue by cyclestudy** [Johnserf-Seed/f2#161]
<img width="1175" alt="image" src="https://github.com/user-attachments/assets/6dee946a-f487-478e-bfcb-657a28cd55e4">
<img width="1150" alt="image" src="https://github.com/user-attachments/assets/eec1983d-81db-46b4-b893-be713065a6fe">
是这个解决方案吗？
`当下载`tiktok`视频时出现`403 Forbidden`错误时，是由于`设备id`被封禁导致的。

`设备id`与生成的`cookie`是一一对应的，如果`设备id`被封禁，那么生成的`cookie`也会被封禁。

解决办法：
1. 运行生成`device_Id`的代码片段，获取新的`device_Id`。
2. 将新的`device_Id`替换到配置文件中。
3. 将新的`cookie`里的值替换到配置文件的`cookie`中（增量非覆盖）。
4. 重新运行下载命令。

代码片段：
https://johnserf-seed.github.io/f2/guide/apps/tiktok/#%E7%94%9F%E6%88%90deviceid-%F0%9F%9F%A2`

解决办法具体怎么操作

**Comment by HentaiBoros** [comment]
直接把你的 `device_id` 粘到 `models` 里就行

https://github.com/Johnserf-Seed/f2/issues/97#issuecomment-2162549431

**Comment by GitHubDer** [comment]
楼主解决了吗

**Comment by cyclestudy** [comment]
> 楼主解决了吗

没有，对小白不太友好

**Comment by JoeanAmier** [comment]
自己改一下 `device_id` 参数。

**Comment by cyclestudy** [comment]
> 自己改一下 `device_id` 参数。

不会修改....

**Comment by Johnserf-Seed** [comment]
#79 #154
