### ISSUE TITLE
[QUESTION]抖音接口返回的图片时 webp, 能改成 jpg 那些么

### ISSUE THREAD

**Issue by immyw** [Johnserf-Seed/f2#171]
- [ ] ~~*在提问时请注意不要包含个人敏感信息*~~
- [ ] 我明白我的提问可能不会得到明确回复或解决。

抖音接口返回的图片时 webp, 能改成 jpg 那些么

**Comment by Johnserf-Seed** [comment]
为了兼容windows`新版照片`改回了`webp`，需要转`jpg`用第三方工具或者用`旧版照片`查看
