### ISSUE TITLE
能否在下载视频时同时下载视频的附带信息以方便分析，例如：点赞数量，评论数量，收藏数量，转发数量

### ISSUE THREAD

**Issue by heartInsert** [Johnserf-Seed/f2#172]
下载视频到本地后我想过滤掉质量低的视频，也就是通过例如点赞数量，评论数量，收藏数量，转发数量这些数据。 所以想保存作品的附带信息，不知道这个建议作者您认为如何?

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/user-attachments/assets/fe4ea4c2-c9cf-4791-9edd-009eaba2ccbd)
目前只对one模式采集的作品添加了入库的操作，未来优化性能之后会开放给其他模式的作品，你可以手动取消在handler的方法下的注释
![image](https://github.com/user-attachments/assets/54ade4c7-6e2c-4fb0-a48e-88d573a2ec3b)
