### ISSUE TITLE
[BUG]抖音配置中通过uid获取到的作者ID是错误的

### ISSUE THREAD

**Issue by Lzy0986** [Johnserf-Seed/f2#174]
f2 版本 0.0.1.6

C:\Users\zhiye>f2 -d DEBUG dy -M one -u "1.07 r@R.xF caN:/ 09/30 大夏天的在陇南冻麻了# 陇南 # 杨杨的日记  https://v.douyin.com/Ceieq4Yx/ 复制此链接，打开Dou音搜索，直接观看视频！"
DEBUG    调试模式：DEBUG
WARNING  您当前使用的版本 0.0.1.6 可能已过时，请考虑及时升级到最新版本 0.0.1.6，请使用 pip install -U f2 更新
INFO     应用：douyin
INFO     模式：one
INFO     主配置路径：E:\Program Files\scoop\apps\python\current\Lib\site-packages\f2\conf\app.yaml
INFO     自定义配置路径：E:\Program Files\scoop\apps\python\current\Lib\site-packages\f2\conf\app.yaml
DEBUG    主配置参数：{'cookie':
         'passport_csrf_token=99bdc07a18decb8e*****;sessionid_ss=e937ef0f45528b353*****;ttwid
         =1%7CCqTxB7TRkCvlg1w7sLwjsXf4HShquOMa9YOLpdE46iM%7C1*****;odin_tt=5b8c5c54c595740cbe92dd9444aef956533562ec75dcf2ea2fc*****;msToken=ZVsYArHQk9GeERD*****', 'naming': '{nickname}_{uid}_{create}_{desc}',
         'path': 'D:\\Download\\Video', 'mode': 'post', 'interval': 'all', 'cover': False, 'music': False, 'desc':
         False, 'folderize': False, 'lyric': False, 'timeout': 10, 'max_retries': 5, 'max_connections': 5, 'max_counts':
         0, 'max_tasks': 10, 'page_counts': 20, 'proxies': {'http://': None, 'https://': None}}
DEBUG    自定义配置参数：{'cookie':
         'passport_csrf_token=99bdc07a18decb8e*****;sessionid_ss=e937ef0f45528b353*****;ttwid
         =1%7CCqTxB7TRkCvlg1w7sLwjsXf4HShquOMa9YOLpdE46iM%7C1*****;odin_tt=5b8c5c54c595740cbe92dd9444aef956533562ec75dcf2ea2fc*****;msToken=ZVsYArHQk9GeERD*****', 'naming': '{nickname}_{uid}_{create}_{desc}',
         'path': 'D:\\Download\\Video', 'mode': 'post', 'interval': 'all', 'cover': False, 'music': False, 'desc':
         False, 'folderize': False, 'lyric': False, 'timeout': 10, 'max_retries': 5, 'max_connections': 5, 'max_counts':
         0, 'max_tasks': 10, 'page_counts': 20, 'proxies': {'http://': None, 'https://': None}}
DEBUG    CLI参数：{'cookie':
         'passport_csrf_token=99bdc07a18decb8e*****;sessionid_ss=e937ef0f45528b353*****;ttwid
         =1%7CCqTxB7TRkCvlg1w7sLwjsXf4HShquOMa9YOLpdE46iM%7C1*****;odin_tt=5b8c5c54c595740cbe92dd9444aef956533562ec75dcf2ea2fc*****;msToken=ZVsYArHQk9GeERD*****', 'naming': '{nickname}_{uid}_{create}_{desc}',
         'path': 'D:\\Download\\Video', 'mode': 'one', 'interval': 'all', 'cover': False, 'music': False, 'desc': False,
         'folderize': False, 'lyric': False, 'timeout': 10, 'max_retries': 5, 'max_connections': 5, 'max_counts': 0,
         'max_tasks': 10, 'page_counts': 20, 'proxies': {'http://': None, 'https://': None}, 'url': '1.07 r@R.xF caN:/
         09/30 大夏天的在陇南冻麻了# 陇南 # 杨杨的日记  https://v.douyin.com/Ceieq4Yx/
         复制此链接，打开Dou音搜索，直接观看视频！', 'languages': 'zh_CN', 'auto_cookie': None, 'headers':
         {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
         Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0', 'Referer': 'https://www.douyin.com/'}}
DEBUG    生成真实的msToken
DEBUG    生成真实的msToken
INFO     开始爬取作品：7402562668936088882
DEBUG    作品详情接口地址：https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=cha
         nnel_pc_web&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1920&scre
         en_height=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Edge&browser_version=122.0.0.0&browse
         r_online=true&engine_name=Blink&engine_version=122.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&device_m
         emory=8&platform=PC&downlink=10&effective_type=4g&round_trip_time=100&msToken=W9WS0mJYdu3XZHhxE7dLsAO46uRaS1wiA
         GeoncWOnvOmq23ThZVYA6C0JZ3k3bIDa_7M65lTrUUO0vMDvYbxMGt6-BUS_1lU9ml07hzccc0VkJPsCknGPK4DIYvEMg==&aweme_id=740256
         2668936088882&a_bogus=Y680Bm82snnsgnWu5f9LfY3q6XZ3YmCG0SVkMD2funfVwL39HMTC9exoZThv1EgjN4/kIeLjy4hbTrCDrQC78Zwf9
         Six/2CZmys0t-Ph5xSSs1feeL8knGJP-vy3SFPp-wN1EcWkqwdCFWRmloae-wHvPjojx2f39gcF
DEBUG    响应状态码: 200
DEBUG    作品ID：7402562668936088882 作品文案：大夏天的在陇南冻麻了#陇南_#杨杨的日记 作者：杨杨很忙_瘦身版_
DEBUG    用户信息接口地址：https://www.douyin.com/aweme/v1/web/user/profile/other/?device_platform=webapp&aid=6383&chann
         el=channel_pc_web&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=192
         0&screen_height=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Edge&browser_version=122.0.0.0&
         browser_online=true&engine_name=Blink&engine_version=122.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&de
         vice_memory=8&platform=PC&downlink=10&effective_type=4g&round_trip_time=100&msToken=W9WS0mJYdu3XZHhxE7dLsAO46uR
         aS1wiAGeoncWOnvOmq23ThZVYA6C0JZ3k3bIDa_7M65lTrUUO0vMDvYbxMGt6-BUS_1lU9ml07hzccc0VkJPsCknGPK4DIYvEMg==&sec_user_
         id=MS4wLjABAAAAwt6NAfXenxf5nGRVNeDCjCxR-atsTZmcM6IEwEDUpJU&a_bogus=mfmwQD83kV9kfj6t5f9LfY3q6-M3YmCG0SVkMD2f5VfV
         LL39HMOs9exoZThvIEyjN4/kIeEjy4hbYr/QrQAj8rjUHWvEWnQ2m6RhKl5Q5xSSs1feeLgQnGJP-vy3SFNm-wN1EcWkqwVnzSRDA99cmhK4bfe
         bY7Y6i6trzf==
DEBUG    响应状态码: 200
DEBUG    单个作品数据：{'admire_count': 72, 'allow_douplus': True, 'allow_share': True, 'animated_cover': None,
         'api_status_code': 0, 'aweme_id': '7402562668936088882', 'aweme_type': 0, 'can_comment': True, 'can_forward':
         True, 'can_share': True, 'can_show_comment': True, 'collect_count': 2047, 'comment_count': 4893, 'comment_gid':
         7402562668936088882, 'cover':
         'https://p3-pc-sign.douyinpic.com/tos-cn-p-0015/o0uL5CXeaeCBTQD7EyLIAXGfD7A2itqQQMeoML~tplv-dy-360p.jpeg?x-expi
         res=1725800400&x-signature=McEKtwUYZlhNWqr7AyDMbkhMZuE%3D&from=327834062&s=PackSourceEnum_AWEME_DETAIL&se=false
         &sc=origin_cover&biz_tag=pcweb_cover&l=20240825214708C683897FB6F4825920E0', 'create_time': '2024-08-13
         18-04-09', 'desc': '大夏天的在陇南冻麻了#陇南_#杨杨的日记', 'desc_raw': '大夏天的在陇南冻麻了#陇南
         #杨杨的日记', 'digg_count': 30132, 'download_setting': None, 'duration': 241672, 'hashtag_ids':
         '["1591826791786500", "1771751457080335"]', 'hashtag_names': '["陇南", "杨杨的日记"]', 'images': [], 'is_ads':
         False, 'is_commerce_music': False, 'is_delete': False, 'is_original': False, 'is_original_sound': True,
         'is_pgc': False, 'is_prohibited': False, 'is_story': 0, 'is_top': 0, 'media_type': 4, 'mix_create_time':
         'Invalid timestamp', 'mix_desc': None, 'mix_desc_raw': None, 'mix_id': None, 'mix_name': None, 'mix_pic_type':
         None, 'mix_share_url': None, 'mix_type': None, 'mix_update_time': 'Invalid timestamp', 'music_author':
         '杨杨很忙_瘦身版_', 'music_author_deleted': False, 'music_author_raw': '杨杨很忙（瘦身版）', 'music_duration':
         241, 'music_id': 7402562697356725001, 'music_mid': '7402562697356725001', 'music_owner_handle': '330024763',
         'music_owner_handle_raw': '330024763', 'music_owner_id': '58620995227', 'music_owner_nickname':
         '杨杨很忙_瘦身版_', 'music_owner_nickname_raw': '杨杨很忙（瘦身版）', 'music_play_url':
         'https://sf3-cdn-tos.douyinstatic.com/obj/ies-music/7402562763473111834.mp3', 'music_status': 1, 'nickname':
         '杨杨很忙_瘦身版_', 'nickname_raw': '杨杨很忙（瘦身版）', 'part_see': 0, 'pgc_author': None, 'pgc_author_raw':
         None, 'pgc_author_title': None, 'pgc_author_title_raw': None, 'pgc_music_type': None, 'position': None,
         'private_status': 0, 'region': 'CN', 'sec_user_id': 'MS4wLjABAAAAwt6NAfXenxf5nGRVNeDCjCxR-atsTZmcM6IEwEDUpJU',
         'seo_ocr_content': None, 'share_count': 11190, 'short_id': '330024763', 'uid': '58620995227', 'unique_id': '',
         'video_bit_rate': [[2551998], [2434589], [1701701], [1568292], [934029], [824705], [874252], [772689]],
         'video_play_addr':
         ['http://v3-web.douyinvod.com/59d6048087b6efaae52cb52df87b1151/66cb60fd/video/tos/cn/tos-cn-ve-15/oE17MQfIGDTXL
         EtQAIeVAziCoLMuTaCD3ye2Cf/?a=6383&ch=26&cr=3&dr=0&lr=all&cd=0%7C0%7C0%7C3&cv=1&br=2492&bt=2492&cs=0&ds=6&ft=AJk
         eU_TLRR0sTlC42Dv2Nc.xBiGNbL_3DUsU_4DgacUJNv7TGW&mime_type=video_mp4&qs=0&rc=ODo7ZDpnNDNlPDg0NzwzOkBpajc2bHY5cnl
         sdDMzNGkzM0A1NTIzNDExX2IxMzYwYC8zYSM0aHBlMmRzbnFgLS1kLTBzcw%3D%3D&btag=c0000e00030000&cquery=100w_100B_100x_100
         z_100o&dy_q=1724593628&feature_id=f0150a16a324336cda5d6dd0b69ed299&l=20240825214708C683897FB6F4825920E0',
         'http://v26-web.douyinvod.com/1775fe6d59157b47f0ab9244eec5679f/66cb60fd/video/tos/cn/tos-cn-ve-15/oE17MQfIGDTXL
         EtQAIeVAziCoLMuTaCD3ye2Cf/?a=6383&ch=26&cr=3&dr=0&lr=all&cd=0%7C0%7C0%7C3&cv=1&br=2492&bt=2492&cs=0&ds=6&ft=AJk
         eU_TLRR0sTlC42Dv2Nc.xBiGNbL_3DUsU_4DgacUJNv7TGW&mime_type=video_mp4&qs=0&rc=ODo7ZDpnNDNlPDg0NzwzOkBpajc2bHY5cnl
         sdDMzNGkzM0A1NTIzNDExX2IxMzYwYC8zYSM0aHBlMmRzbnFgLS1kLTBzcw%3D%3D&btag=c0000e00030000&cquery=100w_100B_100x_100
         z_100o&dy_q=1724593628&feature_id=f0150a16a324336cda5d6dd0b69ed299&l=20240825214708C683897FB6F4825920E0',
         'https://www.douyin.com/aweme/v1/play/?video_id=v0300fg10000cqtiqvvog65shis3k47g&line=0&file_id=6720c934916549e
         bb0414d776a588785&sign=de1029bb80472d06bea73678f04d041a&is_play_url=1&source=PackSourceEnum_AWEME_DETAIL']}
DEBUG    ========7402562668936088882========
DEBUG    {'admire_count': 72, 'allow_douplus': True, 'allow_share': True, 'animated_cover': None, 'api_status_code': 0,
         'aweme_id': '7402562668936088882', 'aweme_type': 0, 'can_comment': True, 'can_forward': True, 'can_share':
         True, 'can_show_comment': True, 'collect_count': 2047, 'comment_count': 4893, 'comment_gid':
         7402562668936088882, 'cover':
         'https://p3-pc-sign.douyinpic.com/tos-cn-p-0015/o0uL5CXeaeCBTQD7EyLIAXGfD7A2itqQQMeoML~tplv-dy-360p.jpeg?x-expi
         res=1725800400&x-signature=McEKtwUYZlhNWqr7AyDMbkhMZuE%3D&from=327834062&s=PackSourceEnum_AWEME_DETAIL&se=false
         &sc=origin_cover&biz_tag=pcweb_cover&l=20240825214708C683897FB6F4825920E0', 'create_time': '2024-08-13
         18-04-09', 'desc': '大夏天的在陇南冻麻了#陇南_#杨杨的日记', 'desc_raw': '大夏天的在陇南冻麻了#陇南
         #杨杨的日记', 'digg_count': 30132, 'download_setting': None, 'duration': 241672, 'hashtag_ids':
         '["1591826791786500", "1771751457080335"]', 'hashtag_names': '["陇南", "杨杨的日记"]', 'images': [], 'is_ads':
         False, 'is_commerce_music': False, 'is_delete': False, 'is_original': False, 'is_original_sound': True,
         'is_pgc': False, 'is_prohibited': False, 'is_story': 0, 'is_top': 0, 'media_type': 4, 'mix_create_time':
         'Invalid timestamp', 'mix_desc': None, 'mix_desc_raw': None, 'mix_id': None, 'mix_name': None, 'mix_pic_type':
         None, 'mix_share_url': None, 'mix_type': None, 'mix_update_time': 'Invalid timestamp', 'music_author':
         '杨杨很忙_瘦身版_', 'music_author_deleted': False, 'music_author_raw': '杨杨很忙（瘦身版）', 'music_duration':
         241, 'music_id': 7402562697356725001, 'music_mid': '7402562697356725001', 'music_owner_handle': '330024763',
         'music_owner_handle_raw': '330024763', 'music_owner_id': '58620995227', 'music_owner_nickname':
         '杨杨很忙_瘦身版_', 'music_owner_nickname_raw': '杨杨很忙（瘦身版）', 'music_play_url':
         'https://sf3-cdn-tos.douyinstatic.com/obj/ies-music/7402562763473111834.mp3', 'music_status': 1, 'nickname':
         '杨杨很忙_瘦身版_', 'nickname_raw': '杨杨很忙（瘦身版）', 'part_see': 0, 'pgc_author': None, 'pgc_author_raw':
         None, 'pgc_author_title': None, 'pgc_author_title_raw': None, 'pgc_music_type': None, 'position': None,
         'private_status': 0, 'region': 'CN', 'sec_user_id': 'MS4wLjABAAAAwt6NAfXenxf5nGRVNeDCjCxR-atsTZmcM6IEwEDUpJU',
         'seo_ocr_content': None, 'share_count': 11190, 'short_id': '330024763', 'uid': '58620995227', 'unique_id': '',
         'video_bit_rate': [[2551998], [2434589], [1701701], [1568292], [934029], [824705], [874252], [772689]],
         'video_play_addr':
         ['http://v3-web.douyinvod.com/59d6048087b6efaae52cb52df87b1151/66cb60fd/video/tos/cn/tos-cn-ve-15/oE17MQfIGDTXL
         EtQAIeVAziCoLMuTaCD3ye2Cf/?a=6383&ch=26&cr=3&dr=0&lr=all&cd=0%7C0%7C0%7C3&cv=1&br=2492&bt=2492&cs=0&ds=6&ft=AJk
         eU_TLRR0sTlC42Dv2Nc.xBiGNbL_3DUsU_4DgacUJNv7TGW&mime_type=video_mp4&qs=0&rc=ODo7ZDpnNDNlPDg0NzwzOkBpajc2bHY5cnl
         sdDMzNGkzM0A1NTIzNDExX2IxMzYwYC8zYSM0aHBlMmRzbnFgLS1kLTBzcw%3D%3D&btag=c0000e00030000&cquery=100w_100B_100x_100
         z_100o&dy_q=1724593628&feature_id=f0150a16a324336cda5d6dd0b69ed299&l=20240825214708C683897FB6F4825920E0',
         'http://v26-web.douyinvod.com/1775fe6d59157b47f0ab9244eec5679f/66cb60fd/video/tos/cn/tos-cn-ve-15/oE17MQfIGDTXL
         EtQAIeVAziCoLMuTaCD3ye2Cf/?a=6383&ch=26&cr=3&dr=0&lr=all&cd=0%7C0%7C0%7C3&cv=1&br=2492&bt=2492&cs=0&ds=6&ft=AJk
         eU_TLRR0sTlC42Dv2Nc.xBiGNbL_3DUsU_4DgacUJNv7TGW&mime_type=video_mp4&qs=0&rc=ODo7ZDpnNDNlPDg0NzwzOkBpajc2bHY5cnl
         sdDMzNGkzM0A1NTIzNDExX2IxMzYwYC8zYSM0aHBlMmRzbnFgLS1kLTBzcw%3D%3D&btag=c0000e00030000&cquery=100w_100B_100x_100
         z_100o&dy_q=1724593628&feature_id=f0150a16a324336cda5d6dd0b69ed299&l=20240825214708C683897FB6F4825920E0',
         'https://www.douyin.com/aweme/v1/play/?video_id=v0300fg10000cqtiqvvog65shis3k47g&line=0&file_id=6720c934916549e
         bb0414d776a588785&sign=de1029bb80472d06bea73678f04d041a&is_play_url=1&source=PackSourceEnum_AWEME_DETAIL']}
DEBUG    ===================================
DEBUG    开始执行下载任务，本次共有 1 个任务
DEBUG    http://v3-web.douyinvod.com/59d6048087b6efaae52cb52df87b1151/66cb60fd/video/tos/cn/tos-cn-ve-15/oE17MQfIGDTXLEt
         QAIeVAziCoLMuTaCD3ye2Cf/?a=6383&ch=26&cr=3&dr=0&lr=all&cd=0%7C0%7C0%7C3&cv=1&br=2492&bt=2492&cs=0&ds=6&ft=AJkeU
         _TLRR0sTlC42Dv2Nc.xBiGNbL_3DUsU_4DgacUJNv7TGW&mime_type=video_mp4&qs=0&rc=ODo7ZDpnNDNlPDg0NzwzOkBpajc2bHY5cnlsd
         DMzNGkzM0A1NTIzNDExX2IxMzYwYC8zYSM0aHBlMmRzbnFgLS1kLTBzcw%3D%3D&btag=c0000e00030000&cquery=100w_100B_100x_100z_
         100o&dy_q=1724593628&feature_id=f0150a16a324336cda5d6dd0b69ed299&l=20240825214708C683897FB6F4825920E0
         在服务器上的总内容长度为：77093334 字节
DEBUG    找到了未下载完的文件 D:\Download\Video\douyin\one\杨杨很忙_瘦身版_\杨杨很忙_瘦身版__58620995227_2024-08-13
         18-04-09_大夏天的在陇南冻麻了#陇南_#杨杨的日记_video.tmp, 大小为 0 字节
DEBUG    下载完成, 文件已保存为 D:\Download\Video\douyin\one\杨杨很忙_瘦身版_\杨杨很忙_瘦身版__58620995227_2024-08-13
         18-04-09_大夏天的在陇南冻麻了#陇南_#杨杨的日记_video.mp4
💛  [  完成  ]:杨杨很忙_瘦身版__5862099522...#陇南_#杨杨的日记_video.mp4 ━━━━━━━━ 100.0% • 77.1/77… 38.1     ETA 0:00:00
                                                                                           MB       MB/s

![下载用户相关信息](https://github.com/user-attachments/assets/f552ba0f-1fa7-4ab7-ac5b-277a14ca5487)
![conf配置](https://github.com/user-attachments/assets/275cda26-ba74-42d4-99e3-2d43e28c20f0)
![CLI命令](https://github.com/user-attachments/assets/377f2389-b4fd-4fa3-ab75-49ac1e2ed174)

**Comment by Johnserf-Seed** [comment]
没有错，uid是`58620995227`有什么问题？`330024763`不叫uid

**Comment by Lzy0986** [comment]
明白了，还以为是抖音号
