### ISSUE TITLE
[FEATRUE / REQUEST]希望能支持多作品合为一个链接的抖音下載

### ISSUE THREAD

**Issue by immyw** [Johnserf-Seed/f2#176]
比如 
7.15 对了我买了18块钱的章鱼小丸子，结果章鱼搜掉了# 甜妹 # 09 https://v.douyin.com/irXxc3GY/ 复制此链接，打开抖音搜索，直接观看视频！ 01/14 [H@V.Ym](mailto:H@V.Ym) AGV:/

電腦端打開會重定向到主頁
手機端能打開這個連接

f2 運行顯示找不到 aweme_id

**Comment by Johnserf-Seed** [comment]
在`0.0.1.7`版本中支持了live图图集的下载
