### ISSUE TITLE
[QUESTION] 运行日志具体项目只显示十个  

### ISSUE THREAD

**Issue by JQKdiantang** [Johnserf-Seed/f2#184]
我是用pycharm 并且用conda的虚拟环境，在pycharm的终端虚拟环境下并且使用命令行运行，

运行命令是 ：f2 dy -c conf/app.yaml  
 但是给出的信息只有：  十条信息 ，但运行一段时间后，使用ctrl+c  进行结束后，才能看到下载详情，但也会随之终止！ 
  配置的文件内容是
  cookie: 
  naming: '{create}_{desc}'
  path: Download
  timeout: 10
  max_retries: 5
  lyric: yes
  max_connections: 5
  max_counts: 0
  max_tasks: 0
  page_counts: 20
  mode: post
  url: https://v.douyin.com
  interval: all
  
  
  
  想请问如果可以实现实时加载更新下载情况？

**Comment by Johnserf-Seed** [comment]
当任务堆积的过多会出现这种情况，可以手动修改代码，实时执行并发任务而非等待每一页处理完再执行。
