### ISSUE TITLE
直播间wss弹幕 🟢 运行10分钟左右就会自动断开

### ISSUE THREAD

**Issue by shaoxia66** [Johnserf-Seed/f2#188]
- [ ] ~~*在提问时请注意不要包含个人敏感信息*~~
- [ ] 我明白我的提问可能不会得到明确回复或解决。

**问题描述**
简要描述你想要获取支持或询问的内容。

**其他细节**
提供任何相关的细节或背景信息，例如你要询问的函数或与项目相关的具体内容。

**截图/代码示例**
如果有必要，可以提供截图或代码示例以更好地说明问题或询问的内容。

**期望的支持**
简要说明你期望从社区或项目维护者那里得到的支持或回答。

**其他**
如果有其他需要补充的内容，请在此处添加。

**Comment by Johnserf-Seed** [comment]
提供一下日志

**Comment by Johnserf-Seed** [comment]
当选择的回调类型在超时时间内没有返回则会关闭连接
