### ISSUE TITLE
[QUESTION]推特的naming中的作品ID参数？

### ISSUE THREAD

**Issue by RallyQ** [Johnserf-Seed/f2#190]
配置文件中抖音naming的作品ID参数是 {aweme_id}
但这个参数用在推特中无效，提示下载失败，去掉这个参数下载成功。但下载时屏显上有显示推文ID的一串数字
想知道推特naming的作品ID参数是啥？
谢谢！

**Comment by Johnserf-Seed** [comment]
`tweet_id`
