### ISSUE TITLE
获取cookie报错

### ISSUE THREAD

**Issue by Loki0612** [Johnserf-Seed/f2#191]
![image](https://github.com/user-attachments/assets/a303dcd4-f9ce-4ddc-9365-cfe3119e8d2b)

把所有浏览器都关闭了之后，还是获取不到cookie昂

**Comment by Johnserf-Seed** [comment]
关闭浏览器后台驻留

**Comment by chanwoood** [comment]
> 关闭浏览器后台驻留 @Johnserf-Seed 

![image](https://github.com/user-attachments/assets/2bcdc6ff-382c-4ed7-8831-05f57d97b843)

**Comment by xiaolinli123** [comment]
另外可手动输入cookie

**Comment by chanwoood** [comment]
> 另外可手动输入cookie

哪个是cookie值呢 @xiaolinli123 
![image](https://github.com/user-attachments/assets/bd36e3e8-d2f2-4652-bc6f-d8dae32f17a6)

**Comment by xiaolinli123** [comment]
![Uploading cookie.png…]()

**Comment by xiaolinli123** [comment]
![cookie](https://github.com/user-attachments/assets/042c968e-f20f-4cfb-81d6-60b4959579cb) @chanwoood

**Comment by chanwoood** [comment]
![image](https://github.com/user-attachments/assets/64cb6520-6e92-471f-b55f-2dd166510c79)
@xiaolinli123 cookie 是这样格式吗？好像不太行

**Comment by xiaolinli123** [comment]
![image](https://github.com/user-attachments/assets/943cf86b-3ae6-47ad-8a77-973e02ff2057)
@chanwoood

**Comment by xiaolinli123** [comment]
- 背景颜色是 `#ffffff` 用于浅色模式，`#000000` 用于深色模式。
- 这是一个 HEX 颜色值：`#0969DA`
- 这是一个 RGB 颜色值：`rgb(9, 105, 218)`
- 这是一个 HSL 颜色值：`hsl(212, 92%, 45%)`

**Comment by chanwoood** [comment]
> ![image](https://private-user-images.githubusercontent.com/154345419/379515928-943cf86b-3ae6-47ad-8a77-973e02ff2057.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NzA1MzgsIm5iZiI6MTcyOTc3MDIzOCwicGF0aCI6Ii8xNTQzNDU0MTkvMzc5NTE1OTI4LTk0M2NmODZiLTNhZTYtNDdhZC04YTc3LTk3M2UwMmZmMjA1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxMTQzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWI2MzZmMTcwMWJmN2VkNDc5NzkzMDJjNTc3MGVhNGQyODRhM2MxODk2MTE5NWViMmI0NDMxOGU4NTY0YWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IuLMZ_kZNe5dTg7wKhbAxXcOj5BMQoFnRasqIL8QYqQ) @chanwoood

谢谢，可以了

**Comment by chanwoood** [comment]
谢谢，可以了 @xiaolinli123

**Comment by howhich** [comment]
您好，请问一下我的抖音网页cookie只有不到三十个字符，不满足常见问题中所提及的cookie长度，同样出现了类似问题。
![image](https://github.com/user-attachments/assets/fbe988a2-3497-4027-9b50-f208171f0628)

**Comment by Johnserf-Seed** [comment]
> 您好，请问一下我的抖音网页cookie只有不到三十个字符，不满足常见问题中所提及的cookie长度，同样出现了类似问题。 ![image](https://private-user-images.githubusercontent.com/112384353/383884975-fbe988a2-3497-4027-9b50-f208171f0628.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NzAwOTcsIm5iZiI6MTczMDk2OTc5NywicGF0aCI6Ii8xMTIzODQzNTMvMzgzODg0OTc1LWZiZTk4OGEyLTM0OTctNDAyNy05YjUwLWYyMDgxNzFmMDYyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QwODU2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGZlZDgxMTNmZDE4YzM0MGVkNjIzOWM0NDAxZTUyYzg1ZjAxODQ4ZTExYjg2YzNmYmYyNmZhMGI5MTFjNmFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CN6YkQhmeayUnxkh2wDwbXKLAWgp3CE43Nsgs1eyOV4)

![image](https://github.com/user-attachments/assets/4523e8c7-f74e-4d5f-9da6-6bb3658f8b24)

**Comment by howhich** [comment]
> > 您好，请问一下我的抖音网页cookie只有不到三十个字符，不满足常见问题中所提及的cookie长度，同样出现了类似问题。 ![image](https://private-user-images.githubusercontent.com/112384353/383884975-fbe988a2-3497-4027-9b50-f208171f0628.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NzAwOTcsIm5iZiI6MTczMDk2OTc5NywicGF0aCI6Ii8xMTIzODQzNTMvMzgzODg0OTc1LWZiZTk4OGEyLTM0OTctNDAyNy05YjUwLWYyMDgxNzFmMDYyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QwODU2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGZlZDgxMTNmZDE4YzM0MGVkNjIzOWM0NDAxZTUyYzg1ZjAxODQ4ZTExYjg2YzNmYmYyNmZhMGI5MTFjNmFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CN6YkQhmeayUnxkh2wDwbXKLAWgp3CE43Nsgs1eyOV4)
> 
> ![image](https://private-user-images.githubusercontent.com/40727745/383886517-4523e8c7-f74e-4d5f-9da6-6bb3658f8b24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NzAzMDUsIm5iZiI6MTczMDk3MDAwNSwicGF0aCI6Ii80MDcyNzc0NS8zODM4ODY1MTctNDUyM2U4YzctZjc0ZS00ZDVmLTlkYTYtNmJiMzY1OGY4YjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA5MDAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMzUzZDU0ZDRhMzgyODdmMWFmYzA3OWM1OWI0N2JmYTdmN2UzZDBiZWE5OTg2OTc0NjM4NTE3NzFmZTcxMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wFcM1duIRCi2mVWO3V0IFGMyNngJzmDAQCZIL0JVFDU)

已解决 感谢！
