### ISSUE TITLE
[QUESTION]想在终端里面直接限制时间范围 错误在哪里啊？

### ISSUE THREAD

**Issue by fuschenkin** [Johnserf-Seed/f2#194]
app.yaml 里面已经删除了 interval:   参数

正确的写法是什么呢？

![微信截图_20241027164627](https://github.com/user-attachments/assets/ef9521ec-acc6-46a7-b181-7b50ba4a0740)

**Comment by Johnserf-Seed** [comment]
参数需要双引号包裹，否则 `|` 将作为管道命令
