### ISSUE TITLE
[BUG]TIKTOK 获取用户主页视频一直提示接口 JSON 失败

### ISSUE THREAD

**Issue by skyhhuc** [Johnserf-Seed/f2#198]
如题，一样的操作，我下载抖音就没有问题，但是tiktok一直报错JSON 接口失败，然后就是响应内容为空，cookie应该是对的，我换了好几个，重新登陆了好几次。以下是报错截图。QA已经全部都看了。
![123](https://github.com/user-attachments/assets/967d67c1-bbbd-4366-83b9-9361db13c7d7)

**Comment by xiaolinli123** [comment]
@skyhhuc 

yaml文件中的格式，以下字段应该用双引号括起来
```
 cookie: "ttwid=xxxxxxx"

**Comment by skyhhuc** [comment]
> @skyhhuc
> 
> yaml文件中的格式，以下字段应该用双引号括起来
> 
> ```
>  cookie: "ttwid=xxxxxxx" 
> ```

我试了，还是提示JSON接口失败，然后响应为空
![999888](https://github.com/user-attachments/assets/a0622465-d2da-449a-99b3-ef29848c77ea)

**Comment by skyhhuc** [comment]
刚才试了一下douyin的，也失败了，昨天都好好的，cookie我也重新换了一个了
![777888](https://github.com/user-attachments/assets/a1968954-b273-46ae-8347-e080a4fdc4ae)

**Comment by xiaolinli123** [comment]
是否升级到最新版本 0.0.1.6，升级请使用
```
 pip install -U f2

**Comment by xiaolinli123** [comment]
@skyhhuc 
是否升级到最新版本 0.0.1.6，升级请使用
```
 pip install -U f2

**Comment by skyhhuc** [comment]
应该是最新版，昨天才在release那里直接下载的

xiaolinli123 ***@***.***> 于 2024年11月10日周日 17:46写道：

**Comment by xiaolinli123** [comment]
@skyhhuc 检查你在cmd中输入的命令是否有错误

**Comment by skyhhuc** [comment]
> @skyhhuc 检查你在cmd中输入的命令是否有错误

你可以帮我看一下吗？我放在截图里面了
![001](https://github.com/user-attachments/assets/35a0b5db-388c-4c0b-a2c0-41a87a5158e8)
![002](https://github.com/user-attachments/assets/b0935773-eb54-41b4-a8b7-a61643a5ef7e)
![003](https://github.com/user-attachments/assets/70953813-3b7f-4f8e-b717-653e939320c1)
![Uploading 004.png…]()

**Comment by xiaolinli123** [comment]
@skyhhuc 
![image](https://github.com/user-attachments/assets/551ed76e-04d2-4a5f-a166-f11413694d98)
请重发004.png

**Comment by xiaolinli123** [comment]
@skyhhuc 
将该移动端url改为网页端url
![image](https://github.com/user-attachments/assets/1a81dc1a-d736-41e4-bdad-cef59dd6119f)

**Comment by skyhhuc** [comment]
还是报错，我改成桌面的了
![005](https://github.com/user-attachments/assets/ab951db6-ee4a-45ce-b3b3-544368720a62)
![006](https://github.com/user-attachments/assets/8c9685e9-c27e-409e-9529-78b86d5c6c6e)
![007](https://github.com/user-attachments/assets/30ee0f99-6a11-427c-a68a-fdd6f85ce52e)
另外我下载douyin的视频应该不用梯子吧？

**Comment by skyhhuc** [comment]
我刚才又试了一下，昨天下载的那个主页的视频，现在还可以下，但是换一个主页的就不行了，就是上面的报错。你可以测试一下

**Comment by skyhhuc** [comment]
可以的主页链接： https://v.douyin.com/iAB6yfvU/
报错的主页链接：https://v.douyin.com/iAU1K1r3/

**Comment by xiaolinli123** [comment]
> 可以的主页链接： https://v.douyin.com/iAB6yfvU/ 报错的主页链接：https://v.douyin.com/iAU1K1r3/

我这边测试两个链接都可以

第二个（也就是你报错的那个链接）其主页是图集式的作品，可能你的报错与此有关。但是我这边虽然有警告，但依旧能成功。

与梯子无关。

**Comment by xiaolinli123** [comment]
@skyhhuc 
请在自定义配置yaml中，使用如下的配置：
```
douyin:
  cookie: null
  cover: null
  desc: null
  folderize: null
  interval: all
  languages: null
  lyric: null
  max_connections: null
  max_counts: null
  max_retries: null
  max_tasks: null
  mode: post
  music: null
  naming: null
  page_counts: null
  path: null
  timeout: null
  url: https://v.douyin.com/iAU1K1r3/

**Comment by skyhhuc** [comment]
那是什么原因啊，你代码截图给我一下，看你是怎么用的，是不是什么参数没设置好？

xiaolinli123 ***@***.***> 于 2024年11月10日周日 22:10写道：

**Comment by xiaolinli123** [comment]
@skyhhuc 
我的主配置yaml:
![image](https://github.com/user-attachments/assets/3ea2d450-e6ad-4034-bd33-adf42cdeaf95)

**Comment by skyhhuc** [comment]
我全部按照你那个来的，还是一样的报错，真是奇了怪了
![101](https://github.com/user-attachments/assets/d4fe61dc-89b1-4074-826d-89887d9c3d19)
![102](https://github.com/user-attachments/assets/92656162-1f70-477e-a704-91f84dfc0587)
![103](https://github.com/user-attachments/assets/42e2d6c3-8c95-40d5-9acf-405dce6bf9d3)

**Comment by xiaolinli123** [comment]
@skyhhuc 主配置yaml里douyin部分改一下试试：
```
douyin:
  cookie: null
  cookie: ttwid= xxx
  naming: '{create}_{desc}'
  path: Download
  timeout: 10
  max_retries: 5
  lyric: yes
  max_connections: 5
  max_counts: 0
  max_tasks: 10
  page_counts: 20

**Comment by skyhhuc** [comment]
我刚才测试了，有问题，然后我尝试更新，确实更新后可以了，douyin的视频试了几个主页都可以，cookie本来加了双引号报错了，不加双引号，反而可以了。
然后我就测试tiktok的主页视频下载，结果还是报错，我把截图放下面了，你有空帮我看看是不是哪里设置还有问题，tiktok到现在我还没成功过
测试链接：https://www.tiktok.com/@luckystore_0070
![1001](https://github.com/user-attachments/assets/36a5bf9f-9d26-40f9-904a-00eb3dfa7fa4)
![1002](https://github.com/user-attachments/assets/75e9703f-88e0-43be-a862-0b4c54e055a8)
![1003](https://github.com/user-attachments/assets/498b6fa5-4215-4048-8c3b-aa020dc343a2)
![1004](https://github.com/user-attachments/assets/00cd341a-28ff-4633-89b6-93200437cb45)

**Comment by skyhhuc** [comment]
大佬有空帮我看一下哈，等你有时间的时候，感谢！！！

**Comment by Johnserf-Seed** [comment]
> 我刚才测试了，有问题，然后我尝试更新，确实更新后可以了，douyin的视频试了几个主页都可以，cookie本来加了双引号报错了，不加双引号，反而可以了。 然后我就测试tiktok的主页视频下载，结果还是报错，我把截图放下面了，你有空帮我看看是不是哪里设置还有问题，tiktok到现在我还没成功过 测试链接：https://www.tiktok.com/@luckystore_0070 ![1001](https://private-user-images.githubusercontent.com/66587321/384697675-36a5bf9f-9d26-40f9-904a-00eb3dfa7fa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzIyNTAsIm5iZiI6MTczMjE3MTk1MCwicGF0aCI6Ii82NjU4NzMyMS8zODQ2OTc2NzUtMzZhNWJmOWYtOWQyNi00MGY5LTkwNGEtMDBlYjNkZmE3ZmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA2NTIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYjA3MDdlZWQzMjdiNDZiODMzMjUyZTBmOTE0OWUyMzNiM2ZlNmQwNWNlNDlkZWNjOTA3M2RlZmY4MjAzMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wSjcdehs7gdmZG44iOIXZ6mcpmkMoM6Mlq1v-wcnhHQ) ![1002](https://private-user-images.githubusercontent.com/66587321/384697678-75e9703f-88e0-43be-a862-0b4c54e055a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzIyNTAsIm5iZiI6MTczMjE3MTk1MCwicGF0aCI6Ii82NjU4NzMyMS8zODQ2OTc2NzgtNzVlOTcwM2YtODhlMC00M2JlLWE4NjItMGI0YzU0ZTA1NWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA2NTIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YWE3NWM3NzYyZTg2OGM5ZWYwZDNkYjA1MjU1N2JjYTI1ZmU3ZjIxYmVkNDc2ZGY1OTk2MzBkMDdmNzFkMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aOG4z3UurdzJpVIRUmV-WwWDmOovCtTpHRBTTtMgK3U) ![1003](https://private-user-images.githubusercontent.com/66587321/384697683-498b6fa5-4215-4048-8c3b-aa020dc343a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzIyNTAsIm5iZiI6MTczMjE3MTk1MCwicGF0aCI6Ii82NjU4NzMyMS8zODQ2OTc2ODMtNDk4YjZmYTUtNDIxNS00MDQ4LThjM2ItYWEwMjBkYzM0M2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA2NTIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNTk2ZTg4YWNkYWU1MTgzYzZkOGI4NjJjOTE0MWEwNWI0YTMxNmEwNTQ3M2UwY2NhMjRlNzhmZGQwOTY5YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wTcn13cFVagw_wS-ywSoUUIFb4SftH32cCl0B3VwilA) ![1004](https://private-user-images.githubusercontent.com/66587321/384697691-00cd341a-28ff-4633-89b6-93200437cb45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzIyNTAsIm5iZiI6MTczMjE3MTk1MCwicGF0aCI6Ii82NjU4NzMyMS8zODQ2OTc2OTEtMDBjZDM0MWEtMjhmZi00NjMzLTg5YjYtOTMyMDA0MzdjYjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA2NTIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZWQ4MWMwZWU3NTQyNjlkYjNhYTM2MTJkMGM3NjE5ZDNjMGExODVmMmQ3OTg2ZDllMGQ1OTIzNWU5NjA2ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rDlowPWiOJLplSx6yEWF60D7ZR4m9aeZ9mK927zV7LI)

![image](https://github.com/user-attachments/assets/9af4d54a-3b78-4eb6-bda2-3ad0222e68ca)

**Comment by skyhhuc** [comment]
我现在更新到0016，你说的重建数据库是怎么操作，有操作指引吗？感谢大佬

**Comment by Johnserf-Seed** [comment]
> 我现在更新到0016，你说的重建数据库是怎么操作，有操作指引吗？感谢大佬

删除下载目录下的`*.db`的文件重新运行即可

**Comment by skyhhuc** [comment]
你说的下载目录是视频的下载目录？视频下载目录我没看到*.db的文件，另外我已经更换了下载目录，还是提示这个。我把代码删了重装了，然后重新弄得cookie，还是提示错误。
![987777](https://github.com/user-attachments/assets/10f21b1c-1f0f-485a-b1cb-f3f1965b58b4)

**Comment by skyhhuc** [comment]
可以的链接：f2 dy -u https://v.douyin.com/iAB6yfvU/ -M post -i all
报错的链接：f2 dy -u https://v.douyin.com/iDerkY3c/  -M post -i all
下面是app.yaml的配置和报错
![123456](https://github.com/user-attachments/assets/ec2cae79-0c76-48b1-86d2-1fccaab9aeb2)
![321123](https://github.com/user-attachments/assets/13c586c3-98c4-4958-9cbc-646e3b8dffb9)

**Comment by skyhhuc** [comment]
tk的一次都没成功过：
测试链接： f2 tk -u https://www.tiktok.com/@luckystore_0070 -M post -i all
报错是跟上面的一样的，大佬麻烦一次性帮我梳理一下，跪谢了！

**Comment by skyhhuc** [comment]
我找到了*.db文件，删除之后重新弄，抖音的目前下载都没问题了，但是tiktok的又出现了403的问题，我按照你说的重新生成deviceId，并且把conf.yaml里面的device id替换为新生成的，然后app.yaml中的cookie个别字段替换成了前面生成的字段(看图片是生成了两个device id的值，我选择下面的那个，然后新生成cookie中是有三个字段的，上面的device id只有一个新字段)，其他的不变，但是还是提示403，然后响应为空，这个是为什么？
![1111](https://github.com/user-attachments/assets/cc57559c-372c-4d36-a41a-897fc437e413)
![22222](https://github.com/user-attachments/assets/46c3d8d0-99ba-458c-9afd-0b2f71a7ab79)
![3333](https://github.com/user-attachments/assets/ce03fedb-acfb-4f01-88f0-c112d525038c)

**Comment by skyhhuc** [comment]
下面是按照新生成的三个字段，我逐一替换了，其他的cookie值不改变
![5555](https://github.com/user-attachments/assets/d09c68f1-55dc-4695-80cf-68cbe04d595c)
![6666](https://github.com/user-attachments/assets/1f768197-8e52-4214-95ad-8d301573ceea)
![7777](https://github.com/user-attachments/assets/d684cb68-acbc-4864-8f03-739bbfc4189b)

**Comment by Johnserf-Seed** [comment]
tiktok 403可看这2条issue #79 #154
