### ISSUE TITLE
[QUESTION] windows系统和mac系统下desc文件名被省略的问题

### ISSUE THREAD

**Issue by CCMonkeyss** [Johnserf-Seed/f2#200]
- [ ] ~~*在提问时请注意不要包含个人敏感信息*~~
- [ ] 我明白我的提问可能不会得到明确回复或解决。

**问题描述**

同样的配置参数
naming: '{nickname}_{create}_{desc}'
下载抖音的视频和图片

windows系统下保存的文件名是：
viviW__2024-11-16 19-34-53__一切都是我_太过骄纵_以为你会懂_#用我知道打开初冬氛围感_#氛围感_#胶片_#电影感_image_1.jpg

mac系统下保存的文件名是：
viviW__2024-11-16 19-34-53__一切都是我_太过骄纵_以为你会懂_#用我知道打......我知道打开初冬氛围感_#氛围感_#胶片_#电影感_image_1.jpg

mac系统保存的文件名desc会被分成两部分，中间加上......，但前后两部分有重复的情况，文件名长度反而比windows系统的文件名长。
请问如何设置才能让mac系统像windows一样保存完整文件名？
谢谢。

**其他细节**
提供任何相关的细节或背景信息，例如你要询问的函数或与项目相关的具体内容。

**截图/代码示例**
如果有必要，可以提供截图或代码示例以更好地说明问题或询问的内容。

**期望的支持**
简要说明你期望从社区或项目维护者那里得到的支持或回答。

**其他**
如果有其他需要补充的内容，请在此处添加。

**Comment by Johnserf-Seed** [comment]
由于不同系统支持的文件名字节长度不同，为了不出错特意设置的，完整的文件名不一定可以保存。

**Comment by CCMonkeyss** [comment]
> 由于不同系统支持的文件名字节长度不同，为了不出错特意设置的，完整的文件名不一定可以保存。

收到，大佬辛苦了
