### ISSUE TITLE
[QUESTION]`fetch_user_profile`请求失败，请更换cookie或稍后再试

### ISSUE THREAD

**Issue by xinchengyou1987** [Johnserf-Seed/f2#206]
换了很多cookie，都出现“响应内容为空, 状态码: 200,”。
请大佬解决一下。
<img width="819" alt="截屏2024-11-24 08 14 25" src="https://github.com/user-attachments/assets/cad3a17c-4715-4fdf-a7dd-0267fc2eeeb5">

**Comment by Johnserf-Seed** [comment]
换登录之后的cookie，还是不行加代理，还是不行重装一遍

**Comment by hungryTechBoy** [comment]
@Johnserf-Seed 一样的问题，使用登录的cookie也不行，是不是抖音改了策略？用了hash校验什么的，我发现query参数改一个无关痛痒的字符就无法返回结果了

**Comment by Johnserf-Seed** [comment]
> [@Johnserf-Seed](https://github.com/Johnserf-Seed) 一样的问题，使用登录的cookie也不行，是不是抖音改了策略？用了hash校验什么的，我发现query参数改一个无关痛痒的字符就无法返回结果了

正确的cookie不会有问题，因为params参数参与ab的加密
![Image](https://github.com/user-attachments/assets/a8da9bf1-e00e-4cee-8988-65622fff903f)

**Comment by hungryTechBoy** [comment]
> > [@Johnserf-Seed](https://github.com/Johnserf-Seed) 一样的问题，使用登录的cookie也不行，是不是抖音改了策略？用了hash校验什么的，我发现query参数改一个无关痛痒的字符就无法返回结果了
> 
> 正确的cookie不会有问题，因为params参数参与ab的加密 ![Image](https://github.com/user-attachments/assets/a8da9bf1-e00e-4cee-8988-65622fff903f)

@Johnserf-Seed 真得奇怪，已经换个无数个cookie了，postman能跑通，就是复制到这个代码不行🥹

**Comment by Johnserf-Seed** [comment]
> > > [@Johnserf-Seed](https://github.com/Johnserf-Seed) 一样的问题，使用登录的cookie也不行，是不是抖音改了策略？用了hash校验什么的，我发现query参数改一个无关痛痒的字符就无法返回结果了
> > 
> > 
> > 正确的cookie不会有问题，因为params参数参与ab的加密 ![Image](https://github.com/user-attachments/assets/a8da9bf1-e00e-4cee-8988-65622fff903f)
> 
> [@Johnserf-Seed](https://github.com/Johnserf-Seed) 真得奇怪，已经换个无数个cookie了，postman能跑通，就是复制到这个代码不行🥹

提供一下主页参数，我测试一下

**Comment by hungryTechBoy** [comment]
> > > > [@Johnserf-Seed](https://github.com/Johnserf-Seed) 一样的问题，使用登录的cookie也不行，是不是抖音改了策略？用了hash校验什么的，我发现query参数改一个无关痛痒的字符就无法返回结果了
> > > 
> > > 
> > > 正确的cookie不会有问题，因为params参数参与ab的加密 ![Image](https://github.com/user-attachments/assets/a8da9bf1-e00e-4cee-8988-65622fff903f)
> > 
> > 
> > [@Johnserf-Seed](https://github.com/Johnserf-Seed) 真得奇怪，已经换个无数个cookie了，postman能跑通，就是复制到这个代码不行🥹
> 
> 提供一下主页参数，我测试一下

@Johnserf-Seed 主页是这个 https://www.douyin.com/user/MS4wLjABAAAAwbbVuf1W2DdgRe0xCa0oxg1ZIHbzuiTzyjq3NcOVgBuu6qIidYlMYqbL3ZFY2swu?from_tab_name=main，我是打开登录后直接复制aweme/v1/web/user/profile/other/路径的curl命令导入postman，这个能通，但是复制cookie+sec_user_id到python代码就不行

![Image](https://github.com/user-attachments/assets/db3ec5b1-ffff-4091-88e1-5af33bd4e91e)

**Comment by Johnserf-Seed** [comment]
> > > > > [@Johnserf-Seed](https://github.com/Johnserf-Seed) 一样的问题，使用登录的cookie也不行，是不是抖音改了策略？用了hash校验什么的，我发现query参数改一个无关痛痒的字符就无法返回结果了
> > > > 
> > > > 
> > > > 正确的cookie不会有问题，因为params参数参与ab的加密 ![Image](https://github.com/user-attachments/assets/a8da9bf1-e00e-4cee-8988-65622fff903f)
> > > 
> > > 
> > > [@Johnserf-Seed](https://github.com/Johnserf-Seed) 真得奇怪，已经换个无数个cookie了，postman能跑通，就是复制到这个代码不行🥹
> > 
> > 
> > 提供一下主页参数，我测试一下
> 
> [@Johnserf-Seed](https://github.com/Johnserf-Seed) 主页是这个 [https://www.douyin.com/user/MS4wLjABAAAAwbbVuf1W2DdgRe0xCa0oxg1ZIHbzuiTzyjq3NcOVgBuu6qIidYlMYqbL3ZFY2swu?from_tab_name=main，](https://www.douyin.com/user/MS4wLjABAAAAwbbVuf1W2DdgRe0xCa0oxg1ZIHbzuiTzyjq3NcOVgBuu6qIidYlMYqbL3ZFY2swu?from_tab_name=main%EF%BC%8C) 我是打开登录后直接复制aweme/v1/web/user/profile/other/路径的curl命令导入postman，这个能通，但是复制cookie+sec_user_id到python代码就不行
> 
> ![Image](https://github.com/user-attachments/assets/db3ec5b1-ffff-4091-88e1-5af33bd4e91e)

我这边测试没问题，你是不是修改了conf.yaml的配置，version_code应该是290100
![Image](https://github.com/user-attachments/assets/801de195-ad6d-4192-bd0a-00b29be3d568)

**Comment by hungryTechBoy** [comment]
> > > > > > [@Johnserf-Seed](https://github.com/Johnserf-Seed) 一样的问题，使用登录的cookie也不行，是不是抖音改了策略？用了hash校验什么的，我发现query参数改一个无关痛痒的字符就无法返回结果了
> > > > > 
> > > > > 
> > > > > 正确的cookie不会有问题，因为params参数参与ab的加密 ![Image](https://github.com/user-attachments/assets/a8da9bf1-e00e-4cee-8988-65622fff903f)
> > > > 
> > > > 
> > > > [@Johnserf-Seed](https://github.com/Johnserf-Seed) 真得奇怪，已经换个无数个cookie了，postman能跑通，就是复制到这个代码不行🥹
> > > 
> > > 
> > > 提供一下主页参数，我测试一下
> > 
> > 
> > [@Johnserf-Seed](https://github.com/Johnserf-Seed) 主页是这个 [https://www.douyin.com/user/MS4wLjABAAAAwbbVuf1W2DdgRe0xCa0oxg1ZIHbzuiTzyjq3NcOVgBuu6qIidYlMYqbL3ZFY2swu?from_tab_name=main，](https://www.douyin.com/user/MS4wLjABAAAAwbbVuf1W2DdgRe0xCa0oxg1ZIHbzuiTzyjq3NcOVgBuu6qIidYlMYqbL3ZFY2swu?from_tab_name=main%EF%BC%8C) 我是打开登录后直接复制aweme/v1/web/user/profile/other/路径的curl命令导入postman，这个能通，但是复制cookie+sec_user_id到python代码就不行
> > ![Image](https://github.com/user-attachments/assets/db3ec5b1-ffff-4091-88e1-5af33bd4e91e)
> 
> 我这边测试没问题，你是不是修改了conf.yaml的配置，version_code应该是290100 ![Image](https://github.com/user-attachments/assets/801de195-ad6d-4192-bd0a-00b29be3d568)

@Johnserf-Seed 没有哎，我pip install 了这个package然后直接复制代码测试，没有改任何配置

**Comment by Johnserf-Seed** [comment]
> > > > > > > [@Johnserf-Seed](https://github.com/Johnserf-Seed) 一样的问题，使用登录的cookie也不行，是不是抖音改了策略？用了hash校验什么的，我发现query参数改一个无关痛痒的字符就无法返回结果了
> > > > > > 
> > > > > > 
> > > > > > 正确的cookie不会有问题，因为params参数参与ab的加密 ![Image](https://github.com/user-attachments/assets/a8da9bf1-e00e-4cee-8988-65622fff903f)
> > > > > 
> > > > > 
> > > > > [@Johnserf-Seed](https://github.com/Johnserf-Seed) 真得奇怪，已经换个无数个cookie了，postman能跑通，就是复制到这个代码不行🥹
> > > > 
> > > > 
> > > > 提供一下主页参数，我测试一下
> > > 
> > > 
> > > [@Johnserf-Seed](https://github.com/Johnserf-Seed) 主页是这个 [https://www.douyin.com/user/MS4wLjABAAAAwbbVuf1W2DdgRe0xCa0oxg1ZIHbzuiTzyjq3NcOVgBuu6qIidYlMYqbL3ZFY2swu?from_tab_name=main，](https://www.douyin.com/user/MS4wLjABAAAAwbbVuf1W2DdgRe0xCa0oxg1ZIHbzuiTzyjq3NcOVgBuu6qIidYlMYqbL3ZFY2swu?from_tab_name=main%EF%BC%8C) 我是打开登录后直接复制aweme/v1/web/user/profile/other/路径的curl命令导入postman，这个能通，但是复制cookie+sec_user_id到python代码就不行
> > > ![Image](https://github.com/user-attachments/assets/db3ec5b1-ffff-4091-88e1-5af33bd4e91e)
> > 
> > 
> > 我这边测试没问题，你是不是修改了conf.yaml的配置，version_code应该是290100 ![Image](https://github.com/user-attachments/assets/801de195-ad6d-4192-bd0a-00b29be3d568)
> 
> [@Johnserf-Seed](https://github.com/Johnserf-Seed) 没有哎，我pip install 了这个package然后直接复制代码测试，没有改任何配置

那你可以切换到最新的分支然后本地安装一次，可能有修复的提交覆盖

**Comment by hungryTechBoy** [comment]
> > > > > > > > [@Johnserf-Seed](https://github.com/Johnserf-Seed) 一样的问题，使用登录的cookie也不行，是不是抖音改了策略？用了hash校验什么的，我发现query参数改一个无关痛痒的字符就无法返回结果了
> > > > > > > 
> > > > > > > 
> > > > > > > 正确的cookie不会有问题，因为params参数参与ab的加密 ![Image](https://github.com/user-attachments/assets/a8da9bf1-e00e-4cee-8988-65622fff903f)
> > > > > > 
> > > > > > 
> > > > > > [@Johnserf-Seed](https://github.com/Johnserf-Seed) 真得奇怪，已经换个无数个cookie了，postman能跑通，就是复制到这个代码不行🥹
> > > > > 
> > > > > 
> > > > > 提供一下主页参数，我测试一下
> > > > 
> > > > 
> > > > [@Johnserf-Seed](https://github.com/Johnserf-Seed) 主页是这个 [https://www.douyin.com/user/MS4wLjABAAAAwbbVuf1W2DdgRe0xCa0oxg1ZIHbzuiTzyjq3NcOVgBuu6qIidYlMYqbL3ZFY2swu?from_tab_name=main，](https://www.douyin.com/user/MS4wLjABAAAAwbbVuf1W2DdgRe0xCa0oxg1ZIHbzuiTzyjq3NcOVgBuu6qIidYlMYqbL3ZFY2swu?from_tab_name=main%EF%BC%8C) 我是打开登录后直接复制aweme/v1/web/user/profile/other/路径的curl命令导入postman，这个能通，但是复制cookie+sec_user_id到python代码就不行
> > > > ![Image](https://github.com/user-attachments/assets/db3ec5b1-ffff-4091-88e1-5af33bd4e91e)
> > > 
> > > 
> > > 我这边测试没问题，你是不是修改了conf.yaml的配置，version_code应该是290100 ![Image](https://github.com/user-attachments/assets/801de195-ad6d-4192-bd0a-00b29be3d568)
> > 
> > 
> > [@Johnserf-Seed](https://github.com/Johnserf-Seed) 没有哎，我pip install 了这个package然后直接复制代码测试，没有改任何配置
> 
> 那你可以切换到最新的分支然后本地安装一次，可能有修复的提交覆盖

@Johnserf-Seed 果然是这样，搞定了，感谢大佬！
