### ISSUE TITLE
[FEATRUE / REQUEST]无法下载4k分辨率

### ISSUE THREAD

**Issue by futianhang** [Johnserf-Seed/f2#209]
网页版显示是4k分辨率，下载只有1080p
https://www.douyin.com/video/7441983254757985595

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/user-attachments/assets/e9044a51-04d5-4456-a658-87eca56bae8b)
新版已支持4k清晰度下载（默认一直都是清晰度最高的那档）

**Comment by futianhang** [comment]
> 直都是清晰度最高的那档）

我用pip更新不到0.0.1.7版本，请问是还没有发布吗？

**Comment by Johnserf-Seed** [comment]
> > 直都是清晰度最高的那档）
> 
> 
> 
> 我用pip更新不到0.0.1.7版本，请问是还没有发布吗？

还在更新文档，暂时没发布

**Comment by futianhang** [comment]
> > > 直都是清晰度最高的那档）
> > 
> > 
> > 我用pip更新不到0.0.1.7版本，请问是还没有发布吗？
> 
> 还在更新文档，暂时没发布

期待ing~
