### ISSUE TITLE
[QUESTION] douyin关注用户列表接口翻页的问题

### ISSUE THREAD

**Issue by hp2577** [Johnserf-Seed/f2#210]
import asyncio
    import json
    from f2.log.logger import logger
    from f2.apps.douyin.handler import DouyinHandler

    kwargs = {
        "headers": {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)     Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0",
            "Referer": "https://www.douyin.com/follow",
        },
        "proxies": {"http://": None, "https://": None},
        "timeout": 1,
        "cookie":,
    }

    async def main():
        user_id = ""  # 公开关注的账号
        sec_user_id = ""  # 公开关注的账号
        # 隐私设置的账号
        # 至少提供user_id或sec_user_id中的一个参数
        # 根据max_time和min_time区间获取关注用户列表
    
        all_data = []
        async for following in DouyinHandler(kwargs).fetch_user_following(
            user_id=user_id,
            sec_user_id=sec_user_id,
            # max_time=1668606509,
            # min_time=0,
        ):
            if following.status_code!= 0:
                logger.error("错误代码：{0} 错误消息：{1}".format(
                    following.status_code, following.status_msg))
            else:
                logger.info(
                    " 用户昵称：{0} ".format(
                       following.nickname,
                    )
                )
                all_data.append(following._to_list())

        with open('following.json', 'w') as f:
           json.dump(all_data, f)

    if __name__ == "__main__":
        asyncio.run(main())  

出处：关注用户数据 🟢异步方法，用于获取指定用户关注的用户列表 

    logger.error_("错误代码：{0} 错误消息：{1}").format(
        following.status_code, following.status_msg)                 
    # 此处AI报错，修改           
    logger.error("错误代码：{0} 错误消息：{1}".format(
        following.status_code, following.status_msg))

    "Referer": "https://www.douyin.com"   
     #修改    
    "Referer": "https://www.douyin.com/follow"
        
我借助AI修改成了以上代码并获取了一个json，但是里面数组的排序不是我抖音的关注顺序（最近关注/最远关注），而是综合排序，所以这个问题该这么处理？
![2](https://github.com/user-attachments/assets/914218e3-3217-4679-bda9-79db19f47794)

**Comment by Johnserf-Seed** [comment]
传入`source_type`参数，`4`为综合，`1`为最近，`3`为最早，同时配合`max_time` 与`min_time`定义时间区间

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/user-attachments/assets/165ea6cc-b858-4b5a-883f-c93b9762d498)

**Comment by hp2577** [comment]
感谢作者回复，我在引入source_type=1这个参数后不管是否指定max_time都会出现以下情况：
    INFO     当前请求的offset：0
    INFO     爬取了 1 个关注用户
    INFO     等待 0 秒后继续
    INFO     当前请求的offset：0
    INFO     爬取了 1 个关注用户
    INFO     等待 0 秒后继续
    INFO     当前请求的offset：0
    INFO     爬取了 1 个关注用户
一直循环并没有采集到任何信息

**Comment by Johnserf-Seed** [comment]
> 感谢作者回复，我在引入source_type=1这个参数后不管是否指定max_time都会出现以下情况： INFO 当前请求的offset：0 INFO 爬取了 1 个关注用户 INFO 等待 0 秒后继续 INFO 当前请求的offset：0 INFO 爬取了 1 个关注用户 INFO 等待 0 秒后继续 INFO 当前请求的offset：0 INFO 爬取了 1 个关注用户 一直循环并没有采集到任何信息

当时只处理了默认的 `4` 类型，现在修复了其他排序的参数问题
![image](https://github.com/user-attachments/assets/dd71ceec-387d-49aa-bc0e-bcf9b191825c)

**Comment by Johnserf-Seed** [comment]
修复代码已经推送，如果着急可以切换 `v0.0.1.7-pw2`分支拉取最新代码，注意方法的一些变动
