### ISSUE TITLE
急求。Seed大佬，下载视频出现FileNotFoundError: [Errno 2] No such file or directory。感觉是{desc}参数太长导致。

### ISSUE THREAD

**Issue by jo-sos** [Johnserf-Seed/f2#215]
下载的视频网址：https://www.douyin.com/user/MS4wLjABAAAAHulzlH6cETVMrnFTuEVrGb6GXcV6pw0S4uC4jQSTUyhnnFtuWs8zryKCcyaM9shm

![屏幕截图](https://github.com/user-attachments/assets/2440be6b-5f4e-49af-b9e1-5f7e553c4c7d)

 - 操作系统: [e.g. Windows 11]
 - 浏览器 [Firefox]
 - 终端 [cmd命令] 
 - F2版本 [0.0.1.6](更新到最新版了）

命令：
f2 dy --auto-cookie firefox

f2  dy  -u https://www.douyin.com/user/MS4wLjABAAAAHulzlH6cETVMrnFTuEVrGb6GXcV6pw0S4uC4jQSTUyhnnFtuWs8zryKCcyaM9shm

配置文件内容：
douyin:
  cookie: 
  cover: false
  desc: no
  folderize: false
  interval: all
  languages: zh_CN
  max_connections: 5
  max_counts: 0
  max_retries: 4
  max_tasks: 6
  mode: post
  music: false
  naming: '{create}_{desc}_{nickname}'
  page_counts: 20
  path: ./Download
  timeout: 6

我试了好多主页，名字短的是成功的。试了好多遍。发现，应该是视频的naming: '{create}_{desc}_{nickname}'原因，{desc}参数的名字太长导致视频文件名和目录路径太长了，才出现下载中途中断。大佬，觉得是这个原因吗？

请求：
在不解除Windows系统中文件名和目录路径的最大长度限制的情况下，如何修改程序中的参数来实现限制{desc}长度，能下载视频成功？具体在哪里修改程序，如何修改程序？麻烦大佬明示。急求。

**Comment by jo-sos** [comment]
修改的文件的文件目录在哪里？

**Comment by jo-sos** [comment]
@dosu  修改的文件的文件目录在哪里？

**Comment by jo-sos** [comment]
@dosu 我没找到format_file_name

**Comment by jo-sos** [comment]
> 下载的视频网址：https://www.douyin.com/user/MS4wLjABAAAAHulzlH6cETVMrnFTuEVrGb6GXcV6pw0S4uC4jQSTUyhnnFtuWs8zryKCcyaM9shm
> 
> ![屏幕截图](https://private-user-images.githubusercontent.com/72454230/395139050-2440be6b-5f4e-49af-b9e1-5f7e553c4c7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMDU2MDgsIm5iZiI6MTczNDAwNTMwOCwicGF0aCI6Ii83MjQ1NDIzMC8zOTUxMzkwNTAtMjQ0MGJlNmItNWY0ZS00OWFmLWI5ZTEtNWY3ZTU1M2M0YzdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDEyMDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNGVjYWQ2Yjg1ODVhYThmNmM3OWVhMTAwOTFjMDIwODFkNmFjNDg5NWVlNDMyYmM5MDlhMDBjOWQwMDBjZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UDcrARWaf0QS5JvSYLQYHaHGtRA3Cs3gHIDWXSsGLcs)
> 
> * 操作系统: [e.g. Windows 11]
> * 浏览器 [Firefox]
> * 终端 [cmd命令]
> * F2版本 [0.0.1.6](更新到最新版了）
> 
> 命令： f2 dy --auto-cookie firefox
> 
> f2 dy -u https://www.douyin.com/user/MS4wLjABAAAAHulzlH6cETVMrnFTuEVrGb6GXcV6pw0S4uC4jQSTUyhnnFtuWs8zryKCcyaM9shm
> 
> 配置文件内容： douyin: cookie: cover: false desc: no folderize: false interval: all languages: zh_CN max_connections: 5 max_counts: 0 max_retries: 4 max_tasks: 6 mode: post music: false naming: '{create}_{desc}_{nickname}' page_counts: 20 path: ./Download timeout: 6
> 
> 我试了好多主页，名字短的是成功的。试了好多遍。发现，应该是视频的naming: '{create}_{desc}_{nickname}'原因，{desc}参数的名字太长导致视频文件名和目录路径太长了，才出现下载中途中断。大佬，觉得是这个原因吗？
> 
> 请求： 在不解除Windows系统中文件名和目录路径的最大长度限制的情况下，如何修改程序中的参数来实现限制{desc}长度，能下载视频成功？具体在哪里修改程序，如何修改程序？麻烦大佬明示。急求。

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/issues/772#issuecomment-2538717190
