### ISSUE TITLE
[QUESTION]咨询一下twitter应该怎么下载

### ISSUE THREAD

**Issue by LRTFK** [Johnserf-Seed/f2#217]
**问题描述**
下载twitter视频的时候，出现了状态码: 403。希望知道正确的获取cookies方式和使用方式。

**截图/代码示例**
INFO     应用：twitter
INFO     模式：post
INFO     主配置路径：D:\Temp\f2\f2\conf\app.yaml
INFO     自定义配置路径：D:\Temp\f2\twi.yaml
WARNING  第 1 次请求响应内容为空, 状态码: 403,
         URL:https://x.com/i/api/graphql/laYnJPCAcVo0o6pzcnlVxQ/UserByScreenName?xxxxxxxxxxxx太长就删了
WARNING  第 2 次请求响应内容为空, 状态码: 403,
         URL:https://x.com/i/api/graphql/laYnJPCAcVo0o6pzcnlVxQ/UserByScreenName?xxxxxxxxxxxx太长就删了
WARNING  第 3 次请求响应内容为空, 状态码: 403,
         URL:https://x.com/i/api/graphql/laYnJPCAcVo0o6pzcnlVxQ/UserByScreenName?xxxxxxxxxxxx太长就删了
WARNING  第 4 次请求响应内容为空, 状态码: 403,
         URL:https://x.com/i/api/graphql/laYnJPCAcVo0o6pzcnlVxQ/UserByScreenName?xxxxxxxxxxxx太长就删了

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/user-attachments/assets/8f7d5acc-e92e-4379-8658-e524c28c7d2e)
需要`X-Csrf-Token`，在网页版开发者控制台中获取

**Comment by LRTFK** [comment]
> ![image](https://private-user-images.githubusercontent.com/40727745/396999242-8f7d5acc-e92e-4379-8658-e524c28c7d2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MzgyODAsIm5iZiI6MTczNDUzNzk4MCwicGF0aCI6Ii80MDcyNzc0NS8zOTY5OTkyNDItOGY3ZDVhY2MtZTkyZS00Mzc5LTg2NTgtZTUyNGMyOGM3ZDJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDE2MDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4Y2Q2Njk1MTUwYWE5M2E2ZTgxNWU5YjE3YTFiNTdkZjU5Y2I4NmM3YTY2NzNhOTQ4MWU1NjYwMTljZmZjMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HAxUQxRhPXWJ6MSiJdKVYxP4UIpwwegmWluLjyIfrY0) 需要`X-Csrf-Token`，在网页版开发者控制台中获取

感谢回复，但是我在yaml中更新了X-Csrf-Token值，运行之后依然不好用，还是403。
我的cookie使用开发者控制台中获取的这个格式的，运行直接出现403报错。
lang=zh-cn; guest_id=xxxxx; night_mode=2; guest_id_marketing=v1%xxxxx; guest_id_ads=v1%xxxxx; kdt=xxxxx; auth_token=xxxxx; ct0=xxxxx; lang=zh-cn; twid=u%xxxxx; _twitter_sess=xxxxx%xxxxx%xxxxx%xxxxx%253D--xxxxx; personalization_id="xxxxx=="
从开发者控制台application中的cookie里面拿_twitter_sess的value放在yaml中的时候，可以进入多次尝试的循环，结果还是403。
所以还是不知道应该用哪个值来使用能运行。

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/user-attachments/assets/26cd356c-b211-4349-ae42-097916474785)
我测试了是正常的，X-Csrf-Token和ck照常填写，原因是你的网络问题，你可以排查一下代理

**Comment by LRTFK** [comment]
感谢回复，回头我再试试吧。我刚刚403的时候其实已经尝试换了一个代理了。。。。

**Comment by Johnserf-Seed** [comment]
> 感谢回复，回头我再试试吧。我刚刚403的时候其实已经尝试换了一个代理了。。。。

我不知道是不是你代理配置的问题，要考虑出口代理支不支持https，后续更新会支持socks5代理

**Comment by LRTFK** [comment]
我直接用的clash的。我在clash切完代理，断开之前的连接重新chrome打开Twitter，之后再使用脚本，还是403。
  proxies: 
    http://: "http://127.0.0.1:7890"
 所以不知道应该怎么操作了

**Comment by Johnserf-Seed** [comment]
> 我直接用的clash的。我在clash切完代理，断开之前的连接重新chrome打开Twitter，之后再使用脚本，还是403。 proxies: http://: "http://127.0.0.1:7890" 所以不知道应该怎么操作了

那还是你的ck，你不需要从应用程序里拿，你在网络里的xhr里找相关接口然后复制请求标头里的ck和X-Csrf-Token到配置文件里

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/user-attachments/assets/19b6e06d-1766-4cb3-b063-6f66632d37ac)
![image](https://github.com/user-attachments/assets/33811af4-7422-41e2-aa88-5bd3b4977624)

所以问题还是你的ck，我是觉得是你的ck格式错了，注意有双引号，所以如果你要放脚本里执行就需要单引号包裹整个ck
![image](https://github.com/user-attachments/assets/67456f3b-03ac-45f8-8cc2-90e76e91423e)

**Comment by LRTFK** [comment]
我的cookie是放在yaml里面的，cookie和X-Csrf-Token都再yaml里面，位置应该无所谓吧。
twitter:
  cookie: guest_id=123455xxxx; night_mode=2; guest_id_marketing=v1%123455xxxx; guest_id_ads=v1%123455xxxx; gt=123455xxxx; kdt=123455xxxx; auth_token=123455xxxx; ct0=123455xxxx; twid=u%123455xxxx; att=1-123455xxxx; personalization_id="v1_RB60dKTB/123455xxxx=="
  X-Csrf-Token: "123455xxxx"
双引号我看到了。在yaml里面整个cookie加不加单引号都会报错。
今天太晚了，明天我也用postman试试，cookie+X-Csrf-Token或者代理，其他的应该没毛病

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/user-attachments/assets/b9f590d8-aa35-4c34-8c0e-f90b5d44cf5d)

**Comment by LRTFK** [comment]
哇，终于找到原因了。不过你这个需要加 X-Csrf-Token的截图，我在文档里面没找到。
改动conf之后能开始下载了，好使了一点点，然后出现了新的问题了
INFO     [  完成  ]： 2024-12-08 13-45-22_Love_life__love_freedom____desc.txt
INFO     [  完成  ]： 2024-12-03 13-46-24_President_Biden_pardoned_his_son_and_it_s_really_hilarious___desc.txt
INFO     [  完成  ]： 2024-12-01 13-31-56_Can_anyone_tell_me_what_Trump_s_tariff_policy_will_do_to_the_United_States__desc.txt
ERROR    httpx 请求错误：https://pbs.twimg.com/media/Gdt3queXcAAgtDW.jpg?format=jpg&name=large，错误详情：
WARNING  链接 https://pbs.twimg.com/media/Gdt3queXcAAgtDW.jpg?format=jpg&name=large 内容长度为0，尝试下一个链接是否可用
WARNING  所有链接都无法下载
ERROR    [  丢失  ]：无法下载文件：2024-12-01

**Comment by Johnserf-Seed** [comment]
> 哇，终于找到原因了。不过你这个需要加 X-Csrf-Token的截图，我在文档里面没找到。 改动conf之后能开始下载了，好使了一点点，然后出现了新的问题了 INFO [ 完成 ]： 2024-12-08 13-45-22_Love_life__love_freedom____desc.txt INFO [ 完成 ]： 2024-12-03 13-46-24_President_Biden_pardoned_his_son_and_it_s_really_hilarious___desc.txt INFO [ 完成 ]： 2024-12-01 13-31-56_Can_anyone_tell_me_what_Trump_s_tariff_policy_will_do_to_the_United_States__desc.txt ERROR httpx 请求错误：[https://pbs.twimg.com/media/Gdt3queXcAAgtDW.jpg?format=jpg&name=large，错误详情：](https://pbs.twimg.com/media/Gdt3queXcAAgtDW.jpg?format=jpg&name=large%EF%BC%8C%E9%94%99%E8%AF%AF%E8%AF%A6%E6%83%85%EF%BC%9A) WARNING 链接 https://pbs.twimg.com/media/Gdt3queXcAAgtDW.jpg?format=jpg&name=large 内容长度为0，尝试下一个链接是否可用 WARNING 所有链接都无法下载 ERROR [ 丢失 ]：无法下载文件：2024-12-01

因为文档还在更新，没有合并到主分支。还是不能下载的情况还是需要你自行来排查原因，因为测试全是通过的

**Comment by LRTFK** [comment]
多谢了
