### ISSUE TITLE
[BUG]第 1732699743000 页没有找到作品

### ISSUE THREAD

**Issue by kosuke-zhang** [Johnserf-Seed/f2#220]
**详细描述错误**
https://github.com/Johnserf-Seed/TikTokDownload/issues/774

在post 模式下下载内容时，使用最新的分支依然出现了问题，希望大佬帮忙看下

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/user-attachments/assets/33837af2-4c5b-4d95-af41-0b1a6faf282e)
![IMG_0972](https://github.com/user-attachments/assets/22ecf9f6-213b-484e-88e5-9020462d8e56)
![image](https://github.com/user-attachments/assets/37b4a99a-8bf7-4e7f-ae3e-c775bf89cfcd)

不是代码的问题，因为10月到5月间隔的比较久，程序是按照接口返回的页码翻页的，抖音默认是15天一页，耐心等待一下就可以了。

也可以适当加大一下`page_counts`这个参数，这样子就有概率把10月份和5月份的作品放一页里返回了。

**Comment by Johnserf-Seed** [comment]
我这边测试下来没有遇到找不到作品的输出，你需要调整一下配置文件
