### ISSUE TITLE
作者大佬：配置浏览器cookie 和 单个视频链接 使用mode: one 模式下载视频会报错，不知道是不是我配置方式不对

### ISSUE THREAD

**Issue by Morii120** [Johnserf-Seed/f2#23]
![image](https://github.com/Johnserf-Seed/f2/assets/13359932/6df8797d-b8d7-44c7-9172-704672751e3a)
![image](https://github.com/Johnserf-Seed/f2/assets/13359932/37c1102f-2f8b-4985-815f-8e6d9a1d19a8)

**Comment by Johnserf-Seed** [comment]
可以更新至`0.0.1.3`版本

**Comment by Morii120** [comment]
感谢大佬 感谢大佬
