### ISSUE TITLE
0.0.13 的几个小问题 （直播链接没有自动省略后面的字串、多用户配置文件 sec_user_id 找不到、配置上的小疑问）

### ISSUE THREAD

**Issue by doio** [Johnserf-Seed/f2#27]
初次尝试 f2，遇到了几个小问题，不知能否解答一下：

1. 之前版本可以直接识别此类直播链接：`https://live.douyin.com/330680364443?enter_from_merge=web_homepage_follow&enter_method=web_live_cover&room_id=7321922315113036210&action_type=click&group_id=undefined&request_id=undefined&is_livehead_preview_mini_window_show=undefined&enter_method_temai=undefined`
   而在 f2 下，会报错：
![Live_Link](https://github.com/Johnserf-Seed/f2/assets/4461202/57ffaed6-cc3d-4df1-9016-eac2e3a5a9a7)

   必须删减掉后面的?以后的字串。能不能后续改进直播链接识别？

2. （疑问）已经从浏览器导入 cookie，并且似乎使用 --init-config dy.yaml 的时候，创建的文件也已经包含了导入的 cookie，可是 AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\conf\app.yaml 里面貌似并没有 cookie 信息？（或者被加密了？）

3. https://johnserf-seed.github.io/f2/site-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6 自定义配置文件下的多用户配置，创建了一个如下文件：
```YAML
douyin:
  # 醒子8ke
  url: https://live.douyin.com/775841227732
  # 直播模式
  mode: live
```
   在 Terminal 里面执行 `f2 -d dy -c C:\Users\o\Desktop\f2\C.yaml`
   会报错提示`ERROR    未在响应的地址中找到sec_user_id, 检查链接是否为用户主页`

   我的疑问是，这是 bug 还是... ？此配置文件是不是不能写这么简单，要使用初始化的带有 cookie 信息的 yaml 作为模板，在其中添加用户信息？如果需要这样添加，能不能改进说明文档，并告知如何添加？
   那么这样一来，多用户配置一多起来的话，万一 cookie 需要更新，工作量会很大？

**Comment by Johnserf-Seed** [comment]
1. 一直都是可以解析所有链接格式的
![image](https://github.com/Johnserf-Seed/f2/assets/40727745/6707ff07-3625-4bb9-9717-508f5349ebf0)

2. 改进了配置文件生成的逻辑，之后的版本用户无需再修改依赖包中配置文件，必须使用初始化配置文件后的自定义配置。

3. 正是因为避免多配置文件造成的修改cookie工作量大，所以存在一个主配置文件，用来存放修改频率低的参数。此自定义配置文件类似cli命令，只需提供高频不同的配置内容即可实现替换。如 https://johnserf-seed.github.io/f2/site-config.html#%E5%A4%9A%E7%94%A8%E6%88%B7%E9%85%8D%E7%BD%AE 所示。

文档会继续更新的，新版本马上推送。

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/f2/commit/697dfaa3403224639de35cc48775828f0cbc8717
https://github.com/Johnserf-Seed/f2/tree/v0.0.1.4-pw1
