### ISSUE TITLE
TK 的 MP4下载失败  其他都能下载  

### ISSUE THREAD

**Issue by JQKdiantang** [Johnserf-Seed/f2#29]
封面  文案  音频都能下载，经过代理下载，页面MP4哪一行显示丢失?

**Comment by HentaiBoros** [comment]
same

**Comment by Johnserf-Seed** [comment]
更换代理线路多试几次，原因是连接到tk视频服务器超时所致

**Comment by DEAN-Cherry** [comment]
> 更换代理线路多试几次，原因是连接到tk视频服务器超时所致

不能复现，甚至使用外网服务器依然不行

**Comment by Johnserf-Seed** [comment]
测试均通过，最新的视频是需要绑定设备id的cookie，查看最新文档获取解决办法
