### ISSUE TITLE
f2安装失败

### ISSUE THREAD

**Issue by Mr-Zhang-Cn** [Johnserf-Seed/f2#30]
我是win10的电脑,
Python 3.12.1
pip 23.3.2 from D:\Program Files\Python312\Lib\site-packages\pip (python 3.12)
安装f2失败
![1705024151619](https://github.com/Johnserf-Seed/f2/assets/90308605/70c14c1b-7d95-490d-b35b-80a585997dc4)

**Comment by Mr-Zhang-Cn** [comment]
不知道怎么弄了.

**Comment by AndersonBY** [comment]
Python 3.11 或者 Python 3.10 应该能装
