### ISSUE TITLE
安装之后不会调用

### ISSUE THREAD

**Issue by fungchunhoeasy** [Johnserf-Seed/f2#32]
刚刚学习 不太懂 我学习安装whl文件后 不知道在终端窗口怎么调用F2

WINDOW
python3.11.3

**Comment by newidingh** [comment]
入口文件是 f2/f2/cli/cli_commands.py，如果想调试，可以修改cli_commands.py中调用main方法的参数，像这样：
if __name__ == "__main__":
    main(['dy', '-h'])

**Comment by fungchunhoeasy** [comment]
PS C:\Users\Administrator> f2 -d dy -c C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\conf\app.yaml -M post -u https://v.douyin.com/iNtoHBCB/
Usage: f2 [OPTIONS] COMMAND [ARGS]...

Error: No such option: -c
PS C:\Users\Administrator> f2 -d dy -c C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\conf\app.yaml -M post -u https://v.douyin.com/iNtoHBCB/ 请问这个要怎么解决啊

**Comment by Johnserf-Seed** [comment]
> PS C:\Users\Administrator> f2 -d dy -c C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\conf\app.yaml -M post -u https://v.douyin.com/iNtoHBCB/
> Usage: f2 [OPTIONS] COMMAND [ARGS]...
> 
> Error: No such option: -c
> PS C:\Users\Administrator> f2 -d dy -c C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\conf\app.yaml -M post -u https://v.douyin.com/iNtoHBCB/ 请问这个要怎么解决啊

f2是0.0.1.4版本吗？ 新版-d多了参数 DEBUG，INFO，WARNING，ERROR
