### ISSUE TITLE
作者大佬，有个别抖音号，文案很长的会下载失败

### ISSUE THREAD

**Issue by darrell0904** [Johnserf-Seed/f2#34]
<img width="851" alt="image" src="https://github.com/Johnserf-Seed/f2/assets/22806990/c4088315-4084-4335-9e11-089a029f3b22">
<img width="1037" alt="image" src="https://github.com/Johnserf-Seed/f2/assets/22806990/6893bf09-b284-4cf0-b229-ecba75bb5f45">
比如抖音主页：https://www.douyin.com/user/MS4wLjABAAAAfsbB7rouS99xoAQUUWC1flpEAfw9eYyBm7x3xV12Ub4

**Comment by darrell0904** [comment]
好想报错了
![image](https://github.com/Johnserf-Seed/f2/assets/22806990/afd1fe70-252f-4f77-9f7e-9631946402d9)

**Comment by darrell0904** [comment]
哦，我懂了，是要这个抖音作者开启视频允许保存到相册，我们才能下载到对应的作品吗？

**Comment by Johnserf-Seed** [comment]
经过我的反复测试，Windows无论是否开启了Win32长路径，该作品都是可以正常下载的。
![image](https://github.com/Johnserf-Seed/f2/assets/40727745/976db92f-fae9-442d-9d54-ec58e2c009cb)
![image](https://github.com/Johnserf-Seed/f2/assets/40727745/370613ff-418a-49a9-8b5c-9848e529f5b2)

**Comment by Johnserf-Seed** [comment]
> 哦，我懂了，是要这个抖音作者开启视频允许保存到相册，我们才能下载到对应的作品吗？

不受该限制的，可以下载作者禁止下载的作品

**Comment by darrell0904** [comment]
> > 哦，我懂了，是要这个抖音作者开启视频允许保存到相册，我们才能下载到对应的作品吗？
> 
> 不受该限制的，可以下载作者禁止下载的作品

感谢作者大大回复，我是 mac，然后步骤也是按照文档一步一步下来的，但好像就是下载不下来，直接就报了我发在上面的问题，这个会跟 m1 系统有关吗？

**Comment by darrell0904** [comment]
这是我的配置文件

![image](https://github.com/Johnserf-Seed/f2/assets/22806990/a9fe9028-99c2-47f8-bb48-c2f5c2147859)

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/Johnserf-Seed/f2/assets/40727745/5f866a9b-fdb1-4ece-b78e-8eaf387abdc6)
在`v0.0.1.4`版本中已修复

**Comment by darrell0904** [comment]
感谢大佬，大佬新年快乐

**Comment by pingping99** [comment]
我遇到了比这更长的文案，还是出现了错误，希望大佬能搞个实在太长的话就截取前面的段落的方案，这样就更加完善了

**Comment by androiddisk** [comment]
> <img alt="image" width="851" src="https://private-user-images.githubusercontent.com/22806990/301099400-c4088315-4084-4335-9e11-089a029f3b22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzU0MTIsIm5iZiI6MTczMzQ3NTExMiwicGF0aCI6Ii8yMjgwNjk5MC8zMDEwOTk0MDAtYzQwODgzMTUtNDA4NC00MzM1LTllMTEtMDg5YTAyOWYzYjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA4NTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNzJlZWViYzQ5NjI3MzA4ZDQ0MzQ2YzZlYjc3YjM5ZTAxMGU0ZTJiYTRkMmM3N2Q3OTdiOWJlYzgzZmJkOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Q7LFrB_9MLIs0F5ZOHozcv81yb1a7RQZpQ43ndc_ylE"> <img alt="image" width="1037" src="https://private-user-images.githubusercontent.com/22806990/301099467-6893bf09-b284-4cf0-b229-ecba75bb5f45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzU0MTIsIm5iZiI6MTczMzQ3NTExMiwicGF0aCI6Ii8yMjgwNjk5MC8zMDEwOTk0NjctNjg5M2JmMDktYjI4NC00Y2YwLWIyMjktZWNiYTc1YmI1ZjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA4NTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0YWNjYWZkMDFmZDE3NTI5NmQ0NjBhMGZhZGM0NTIwMjdjMDdhYjg4YjNlMmZiNWYzODMxM2JlMDlhZTUxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.txrjRh1GmNakTPzk6e6Vq_3rB0bNbB58b6v31-k06Io"> 比如抖音主页：https://www.douyin.com/user/MS4wLjABAAAAfsbB7rouS99xoAQUUWC1flpEAfw9eYyBm7x3xV12Ub4

你的cookie怎么不一样呢
