### ISSUE TITLE
请问作者大佬，使用该代理可以访问tiktok，但是下载却报错是什么原因呢

### ISSUE THREAD

**Issue by Phoenix-Pl** [Johnserf-Seed/f2#35]
PS F:\Tiktok Downloads> f2 tk -c tk.yaml
INFO     App: tiktok
INFO     主配置： conf/app.yaml
INFO     自定义配置： tk.yaml
请前往QA文档 https://johnserf-seed.github.io/f2/question-answer/qa.html 查看相关帮助
Error: 连接端点失败，检查网络环境或代理:
https://mssdk-sg.tiktok.com/web/common?msToken=1Ab-7YxR9lUHSem0PraI_XzdKmpHb6j50L8AaXLAd2aWTdoJCYLfX_67rVQFE4UwwHVHmyG_N
fIipqrlLT3kCXps-5PYlNAqtdwEg7TrDyTAfCKyBrOLmhMUjB55oW8SPZ4_EkNxNFUdV7MquA== 代理：{'http://': 'http://127.0.0.1:10809',
'https://': 'http://127.0.0.1:10809'}.
ERROR    Error: 连接端点失败，检查网络环境或代理:
         https://mssdk-sg.tiktok.com/web/common?msToken=1Ab-7YxR9lUHSem0PraI_XzdKmpHb6j50L8AaXLAd2aWTdoJCYLfX_67rVQFE4Uw
         wHVHmyG_NfIipqrlLT3kCXps-5PYlNAqtdwEg7TrDyTAfCKyBrOLmhMUjB55oW8SPZ4_EkNxNFUdV7MquA== 代理：{'http://':
         'http://127.0.0.1:10809', 'https://': 'http://127.0.0.1:10809'}.

**Comment by Johnserf-Seed** [comment]
更换其他节点再尝试

**Comment by Phoenix-Pl** [comment]
> 更换其他节点再尝试

好的，感谢大佬回复
