### ISSUE TITLE
自定义配置文件path配置不生效

### ISSUE THREAD

**Issue by KYSauber** [Johnserf-Seed/f2#36]
系统：MacOS
问题：
自定义配置文件是先初始化生成的，再修改其中的配置；
path 设置了绝对路径，执行命令 f2 dy -c <自定义配置文件> ，会在运行该命令的当前目录下创建Download文件夹，配置文件中的path无法生效。

**Comment by NormanMises** [comment]
嗯 发现确实是不生效的   上面的图是因为我在download里打开cmd下载的 我还以为是程式设定的套娃下载路径 结果今天在默认c盘打开cmd下载直接下c盘去了。。。

**Comment by Johnserf-Seed** [comment]
`0.0.1.4`版本修复了默认参数与配置文件冲突造成的问题，等新版推送吧

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/f2/commit/697dfaa3403224639de35cc48775828f0cbc8717
