### ISSUE TITLE
配置文件到底是yes还是true？

### ISSUE THREAD

**Issue by NormanMises** [Johnserf-Seed/f2#37]
![image](https://github.com/Johnserf-Seed/f2/assets/38835726/a086ca34-c88a-4ad1-8401-e15d4b415f34)
![image](https://github.com/Johnserf-Seed/f2/assets/38835726/3c66cb9f-f60d-4f5f-bc86-172ccb63ce6f)
如图 doc里写yes 初始化的文件里是true？

**Comment by NormanMises** [comment]
是true false 一更新文件全变成这俩了

**Comment by Johnserf-Seed** [comment]
这些参数均可 'true'、'false'、'yes'、'no'、'on'、'off'、'1'、'0'（不区分大小写）

**Comment by NormanMises** [comment]
我天 还是统一一下吧 不然不一致很难受啊

**Comment by Johnserf-Seed** [comment]
自己选择就好，不需要统一
