### ISSUE TITLE
命令报错

### ISSUE THREAD

**Issue by QQ920924960** [Johnserf-Seed/f2#42]
<img width="993" alt="image" src="https://github.com/Johnserf-Seed/f2/assets/7412045/838485fa-f79e-4fc6-b2aa-09489418890d">

**Comment by Johnserf-Seed** [comment]
不要使用入口文件来下载，如果无法使用f2命令请查看文档帮助。 https://johnserf-seed.github.io/f2/question-answer/qa.html#f2-command-not-found

**Comment by QQ920924960** [comment]
好的，谢谢

**Comment by QQ920924960** [comment]
就很奇怪，旧版本除了收藏的视频没法下载，其他到能正常使用，今天用f2-0.0.1.4版本，就一直提示【没有找到符合条件的作品】，看了下自己的配置感觉也没错
<img width="864" alt="image" src="https://github.com/Johnserf-Seed/f2/assets/7412045/52b9e2bd-3fec-4940-b224-3974dee068f6">
<img width="617" alt="image" src="https://github.com/Johnserf-Seed/f2/assets/7412045/7a16ad10-0d11-4753-a43b-7d9c0f395980">

**Comment by shichuanenhui** [comment]
一样，我下抖音也是这个问题，没找到符合条件作品0.0.1.4，，1.3的没这个问题

**Comment by Johnserf-Seed** [comment]
加上`f2 -d DEBUG -c app.yaml`可以很清楚的看见哪些参数是没有配置的

**Comment by QQ920924960** [comment]
**感觉这个版本还不是很稳定，不过还是感谢大佬在百忙中回复我**

<img width="1028" alt="image" src="https://github.com/Johnserf-Seed/f2/assets/7412045/fe2615c8-4aec-4d7f-87da-24da55f119e4">

**Comment by Johnserf-Seed** [comment]
> **感觉这个版本还不是很稳定，不过还是感谢大佬在百忙中回复我**
> 
> <img alt="image" width="1028" src="https://private-user-images.githubusercontent.com/7412045/306596021-fe2615c8-4aec-4d7f-87da-24da55f119e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MTMyNjIsIm5iZiI6MTcwODUxMjk2MiwicGF0aCI6Ii83NDEyMDQ1LzMwNjU5NjAyMS1mZTI2MTVjOC00YWVjLTRkN2YtODdkYS0yNGRhNTVmMTE5ZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMTA1NjAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjliMWU0ZmJiZThjYWI0ODBiZGMzMGRlMjQxZjZhMTBkNjU1OGQ5YzFiNDBmZmNiNDM5NjdiZDNkZjBmNTk2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iSPbKYFIVl0vcu-D30nQ0b0YhI5inB21R50uAxY38ZM">

![image](https://github.com/Johnserf-Seed/f2/assets/40727745/5fa728b9-ebbd-4a53-bb83-ea778bc7b3fb)
测试了，一切都正常的，不稳定的话不会发版本的。收藏接口是根据用户登录的cookie来获取该用户的收藏作品，你可以重新获取一下新的cookie再试。

**Comment by QQ920924960** [comment]
刚才重新获取了cookie，又报下面的这个错误

<img width="831" alt="image" src="https://github.com/Johnserf-Seed/f2/assets/7412045/d893aef5-9b3e-4981-800d-8fc9e45b3c02">

**Comment by Johnserf-Seed** [comment]
> 刚才重新获取了cookie，又报下面的这个错误
> 
> <img alt="image" width="831" src="https://private-user-images.githubusercontent.com/7412045/306603320-d893aef5-9b3e-4981-800d-8fc9e45b3c02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MTQ4MzAsIm5iZiI6MTcwODUxNDUzMCwicGF0aCI6Ii83NDEyMDQ1LzMwNjYwMzMyMC1kODkzYWVmNS05YjNlLTQ5ODEtODAwZC04ZmM5ZTQ1YjNjMDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMTEyMjEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTY3MDRhMTY0NmE3ODEyMGFhNThjYjI4YjczODkxZjZlNTlkOWZlYmVlNzRkOWRlNzMzN2JmNjYzOGZhYmRlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JIoC84u3exsSFl1ELqqgmlo5L54dRZilEm5qjAF87IY">

这个就可能和你的python版本有关系了，你在#43也是一样的报错，3.9可能对异步的特性不是很支持。你可以尝试更新到3.11.1以后的版本

**Comment by QQ920924960** [comment]
好的，感谢，我试试

**Comment by Johnserf-Seed** [comment]
如果`macOS <= 10.8`也可能出现一些意外的错误

**Comment by QQ920924960** [comment]
你好，配置文件有没有提供一个完整的模板，仔细看报错的地方发现好像是我interval的值设定错了

**Comment by Johnserf-Seed** [comment]
> 你好，配置文件有没有提供一个完整的模板，仔细看报错的地方发现好像是我interval的值设定错了

可以使用`--init-config`初始化新的配置文件。

**Comment by QQ920924960** [comment]
感谢感谢，这回全部妥妥的弄好了

**Comment by EsperantoP** [comment]
这里我还想说一下关于不能下载收藏夹内的视频呐
我的是直接--auto-cookie指令直接更新了我本地配置文件的cookie就可以了。
当然我是私密账号，所以也还尝试了对我自己的账号鼓捣，然后变成了一坨。
所以建议大家先看这个issue再对自己的抖音下手 😥😥😥
