### ISSUE TITLE
How to config to download all my douyin collect video

### ISSUE THREAD

**Issue by ruijerd99** [Johnserf-Seed/f2#44]
The tool ask the url, i try to put my account url but it not work. Thanks

**Comment by Johnserf-Seed** [comment]
> The tool ask the url, i try to put my account url but it not work. Thanks

Can you provide more information? For example, configuration files and logs, which will quickly solve your problem screenshot.

**Comment by ruijerd99** [comment]
thanks for quick response
here is my config 
![image](https://github.com/Johnserf-Seed/f2/assets/114635203/72a7d1b8-a1df-4d6d-9345-0a819ae05090)
and terminal
![image](https://github.com/Johnserf-Seed/f2/assets/114635203/a41bf61a-a392-4b0e-8af6-ce1bd4135b12)

**Comment by Johnserf-Seed** [comment]
One more thing, cli plus `-l en_US`. You can translate the output into English.

**Comment by ruijerd99** [comment]
Thank you for your help, I have made it to this step. 
![image](https://github.com/Johnserf-Seed/f2/assets/114635203/c68861b3-be0a-4d1b-a27d-42f667e425fa)
but what is url to download all my account favorite video? do i need create a collection and add all favorite video to it and get url?

**Comment by Johnserf-Seed** [comment]
> Thank you for your help, I have made it to this step. 
> ![image](https://github.com/Johnserf-Seed/f2/assets/114635203/c68861b3-be0a-4d1b-a27d-42f667e425fa)
> but what is url to download all my account favorite video? do i need create a collection and add all favorite video to it and get url?

douyin's collection videos only need to provide the homepage link of the account, and at the same time, it is necessary to ensure that the cookie of the account is filled in.
If it is a favorite video, you only need to change the download mode to `like`.

**Comment by Johnserf-Seed** [comment]
> Oh I mean collection video. I try to put my account link like "https://www.douyin.com/user/MS4wLjABAAAAcbXFFa_9bpVypYOoK20Hn2FxLY4cJ3jXBYM6XwSefsc" but it not download anything, maybe my cookie is wrong ?

Yes, you can switch the download mode to test whether cookies are available. If you can't download the collection video, you can get a new cookie again.

**Comment by ruijerd99** [comment]
now it work. thanks for your help and your tools <3
