### ISSUE TITLE
macos|tk|报错：AttributeError: 'dict' object has no attribute 'get_video_info'

### ISSUE THREAD

**Issue by tianlelyd** [Johnserf-Seed/f2#45]
具体报错：
<img width="1397" alt="image" src="https://github.com/Johnserf-Seed/f2/assets/5620472/123a411c-b6c5-4bd4-b5bf-5b89bdd7da67">
配置文件如下：
<img width="296" alt="image" src="https://github.com/Johnserf-Seed/f2/assets/5620472/dba5a8b9-3da1-46fd-907f-bce1cd0b0f34">
系统环境：
macos：14.1.1
python：3.9.6

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/f2/commit/f12cc977c62c6f71a82b547ea0f3f9be257afdfd
参考此提交修改一下本地代码

**Comment by tianlelyd** [comment]
修改后不报错了，但是下载提示“WARNING  没有找到符合条件的作品”
<img width="815" alt="image" src="https://github.com/Johnserf-Seed/f2/assets/5620472/7e94b314-9e69-48c8-adf5-97806227f76d">
我运行的命令如下`f2 tk -M one -u https://www.tiktok.com/@openai/video/7339045312423578922 -c ./app.yaml`

**Comment by Johnserf-Seed** [comment]
> 修改后不报错了，但是下载提示“WARNING  没有找到符合条件的作品”
> <img width="815" alt="image" src="https://github.com/Johnserf-Seed/f2/assets/5620472/7e94b314-9e69-48c8-adf5-97806227f76d">
> 我运行的命令如下`f2 tk -M one -u https://www.tiktok.com/@openai/video/7339045312423578922 -c ./app.yaml`

因为你的配置文件里没有设置interval，或者在命令行加上-i all

**Comment by tianlelyd** [comment]
```
f2 tk -M one -u https://www.tiktok.com/@openai/video/7338441338305711402 -c ./app.yaml
INFO     App: tiktok
INFO     主配置路径： /Users/yandongli/Library/Python/3.9/lib/python/site-packages/f2/conf/app.yaml
INFO     自定义配置路径： /Users/yandongli/tools/myspace/test/jstest/app.yaml
ERROR    HTTP状态错误, 尝试GET请求失败:
         https://v16-webapp-prime.tiktok.com/video/tos/maliva/tos-maliva-ve-0068c799-us/o4JL9QkGLCYefOBLIDosXAI6IH6XersA3jEZX3/?a=1988&ch=0&cr=3&dr=0&lr=unwatermarked&cd=0%7C
         0%7C0%7C&cv=1&br=2970&bt=1485&bti=ODszNWYuMDE6&cs=0&ds=6&ft=4fUEKMwF8Zmo0puOT94jVAL0ypWrKsd.&mime_type=video_mp4&qs=0&rc=ZjNlOGhoOjQ2PDs5M2doOUBpanlucHk5cnhwcTMzZzcz
         NEAwXjFjNF8zNV4xLTRiMV9fYSMxLnNiMmRzL19gLS1kMS9zcw%3D%3D&btag=e00088000&expire=1708799804&l=20240224123622125038BFE9EA382F2DF5&ply_type=2&policy=2&signature=66b375ef
         a501ad16ddea9894cbfbcc8b&tk=tt_chain_token, 错误详情: Client error '403 Forbidden' for url
         'https://v16-webapp-prime.tiktok.com/video/tos/maliva/tos-maliva-ve-0068c799-us/o4JL9QkGLCYefOBLIDosXAI6IH6XersA3jEZX3/?a=1988&ch=0&cr=3&dr=0&lr=unwatermarked&cd=0%7
         C0%7C0%7C&cv=1&br=2970&bt=1485&bti=ODszNWYuMDE6&cs=0&ds=6&ft=4fUEKMwF8Zmo0puOT94jVAL0ypWrKsd.&mime_type=video_mp4&qs=0&rc=ZjNlOGhoOjQ2PDs5M2doOUBpanlucHk5cnhwcTMzZzc
         zNEAwXjFjNF8zNV4xLTRiMV9fYSMxLnNiMmRzL19gLS1kMS9zcw%3D%3D&btag=e00088000&expire=1708799804&l=20240224123622125038BFE9EA382F2DF5&ply_type=2&policy=2&signature=66b375e
         fa501ad16ddea9894cbfbcc8b&tk=tt_chain_token'
         For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403
WARNING  内容长度为0，跳过下载
💛  [  丢失  ]:2024-02-22 23-00-34_...ra_#openai_video.mp4 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0.0% • 0/? bytes ? ETA
```
依然不能下载，我尝试用游戏cookie和登录的cookie都是一样的

**Comment by Johnserf-Seed** [comment]
> ```
> f2 tk -M one -u https://www.tiktok.com/@openai/video/7338441338305711402 -c ./app.yaml
> INFO     App: tiktok
> INFO     主配置路径： /Users/yandongli/Library/Python/3.9/lib/python/site-packages/f2/conf/app.yaml
> INFO     自定义配置路径： /Users/yandongli/tools/myspace/test/jstest/app.yaml
> ERROR    HTTP状态错误, 尝试GET请求失败:
>          https://v16-webapp-prime.tiktok.com/video/tos/maliva/tos-maliva-ve-0068c799-us/o4JL9QkGLCYefOBLIDosXAI6IH6XersA3jEZX3/?a=1988&ch=0&cr=3&dr=0&lr=unwatermarked&cd=0%7C
>          0%7C0%7C&cv=1&br=2970&bt=1485&bti=ODszNWYuMDE6&cs=0&ds=6&ft=4fUEKMwF8Zmo0puOT94jVAL0ypWrKsd.&mime_type=video_mp4&qs=0&rc=ZjNlOGhoOjQ2PDs5M2doOUBpanlucHk5cnhwcTMzZzcz
>          NEAwXjFjNF8zNV4xLTRiMV9fYSMxLnNiMmRzL19gLS1kMS9zcw%3D%3D&btag=e00088000&expire=1708799804&l=20240224123622125038BFE9EA382F2DF5&ply_type=2&policy=2&signature=66b375ef
>          a501ad16ddea9894cbfbcc8b&tk=tt_chain_token, 错误详情: Client error '403 Forbidden' for url
>          'https://v16-webapp-prime.tiktok.com/video/tos/maliva/tos-maliva-ve-0068c799-us/o4JL9QkGLCYefOBLIDosXAI6IH6XersA3jEZX3/?a=1988&ch=0&cr=3&dr=0&lr=unwatermarked&cd=0%7
>          C0%7C0%7C&cv=1&br=2970&bt=1485&bti=ODszNWYuMDE6&cs=0&ds=6&ft=4fUEKMwF8Zmo0puOT94jVAL0ypWrKsd.&mime_type=video_mp4&qs=0&rc=ZjNlOGhoOjQ2PDs5M2doOUBpanlucHk5cnhwcTMzZzc
>          zNEAwXjFjNF8zNV4xLTRiMV9fYSMxLnNiMmRzL19gLS1kMS9zcw%3D%3D&btag=e00088000&expire=1708799804&l=20240224123622125038BFE9EA382F2DF5&ply_type=2&policy=2&signature=66b375e
>          fa501ad16ddea9894cbfbcc8b&tk=tt_chain_token'
>          For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403
> WARNING  内容长度为0，跳过下载
> 💛  [  丢失  ]:2024-02-22 23-00-34_...ra_#openai_video.mp4 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0.0% • 0/? bytes ? ETA
> ```
> 依然不能下载，我尝试用游戏cookie和登录的cookie都是一样的

你可以查查403是什么报错，这个和代码无关和你的代理网络有关。
