### ISSUE TITLE
Windows|在使用-c命令时报错

### ISSUE THREAD

**Issue by PEClound** [Johnserf-Seed/f2#48]
![image](https://github.com/Johnserf-Seed/f2/assets/117785711/b310cea2-05f3-4fa9-8310-b82e2b4a17d8)
![image](https://github.com/Johnserf-Seed/f2/assets/117785711/bc2fe94e-a3c2-4dc0-9e71-92067a3f34e9)
Error: No such option: -c 错误：没有这样的选项：-c 这是怎么回事？我该怎么解决？

**Comment by PEClound** [comment]
![image](https://github.com/Johnserf-Seed/f2/assets/117785711/68549082-ad6e-4c58-8b30-3beef94c2000)
![屏幕截图 2024-02-28 172751](https://github.com/Johnserf-Seed/f2/assets/117785711/70bb7f2f-1118-400a-abe1-93083bf02039)
这是为什么？

**Comment by Johnserf-Seed** [comment]
> ![image](https://github.com/Johnserf-Seed/f2/assets/117785711/68549082-ad6e-4c58-8b30-3beef94c2000)
> ![屏幕截图 2024-02-28 172751](https://github.com/Johnserf-Seed/f2/assets/117785711/70bb7f2f-1118-400a-abe1-93083bf02039)
> 这是为什么？

https://github.com/Johnserf-Seed/TikTokDownload/issues/660

**Comment by PEClound** [comment]
作者nb

**Comment by PEClound** [comment]
作者 它默认下载到哪里？

**Comment by Johnserf-Seed** [comment]
> 作者 它默认下载到哪里？
> 

需要自己配置，取消了默认参数

**Comment by PEClound** [comment]
所以说没配置下载就相当于没保存对吗？

**Comment by PEClound** [comment]
所以说没配置下载路径下载就没保存对吧？

**Comment by Johnserf-Seed** [comment]
> 所以说没配置下载路径下载就没保存对吧？

没配置则会报错
