### ISSUE TITLE
没有找到符合要求的作品[QUESTION]

### ISSUE THREAD

**Issue by zh7606559342012** [Johnserf-Seed/f2#51]
D:\go_project\src\f2>f2 dy -c D:\go_project\src\f2\huawei.yaml
INFO     App: douyin
INFO     主配置路径： D:\go_project\src\f2\f2\conf\app.yaml
INFO     自定义配置路径： D:\go_project\src\f2\huawei.yaml
WARNING  没有找到符合条件的作品

已经导入了cookies
huawei.yaml
douyin:
  # 浩子
  url: https://www.douyin.com/user/MS4wLjABAAAAn7sRyhIb1IuoDxEJ5iYG2lCWvuVaqTjNV_WiAi8Kt60?vid=7334935799592439074
  # 主页作品
  mode: post

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/issues/660

**Comment by zh7606559342012** [comment]
太给力了，大佬
