### ISSUE TITLE
[BUG] 不能下载全部视频，每次视频下多一点就报错

### ISSUE THREAD

**Issue by Ikervs** [Johnserf-Seed/f2#53]
如图
![Uploading 报错.png…]()

**Comment by 1153439431** [comment]
![报错](https://github.com/Johnserf-Seed/f2/assets/83049805/eba7f78d-0dd9-4b55-a084-6f01302b5fa7)
![报错](https://github.com/Johnserf-Seed/f2/assets/83049805/e9499637-118a-4d43-8bf5-d9c7bd8c8cbd)

**Comment by Geek-zhihao** [comment]
@Johnserf-Seed 大佬我在这提个小小的优化建议，步骤如下：
一、先进行第一页作品信息解析，即max_cursor = 0的页，将当前页的作品信息保存到数据库里。
二、从上一页的响应中获取下一页的max_cursor，循环访问，直到has_more = 0，将每一页的作品信息保存到数据库里。
三、再根据配置文件里配置，比如筛选指定时间内作品，从数据库中提取需要保存的作品的信息。
四、将提取的信息传递给下载程序进行队列处理。
以上只是我的大概思路，实际开发可能还要加入从上次错误处重新加载等其他功能。将所有信息解析保存在本地再下载这个思路我想可能会大大改善网络问题带来的程序崩溃。

**Comment by Johnserf-Seed** [comment]
> @Johnserf-Seed 大佬我在这提个小小的优化建议，步骤如下： 一、先进行第一页作品信息解析，即max_cursor = 0的页，将当前页的作品信息保存到数据库里。 二、从上一页的响应中获取下一页的max_cursor，循环访问，直到has_more = 0，将每一页的作品信息保存到数据库里。 三、再根据配置文件里配置，比如筛选指定时间内作品，从数据库中提取需要保存的作品的信息。 四、将提取的信息传递给下载程序进行队列处理。 以上只是我的大概思路，实际开发可能还要加入从上次错误处重新加载等其他功能。将所有信息解析保存在本地再下载这个思路我想可能会大大改善网络问题带来的程序崩溃。

抖音主页接口是支持指定某个作品开始返回的，所以数据库中我保存了最后一次采集的作品id，这个功能其实是留给开发者用的
