### ISSUE TITLE
[BUG] tuple index out of range

### ISSUE THREAD

**Issue by EsperantoP** [Johnserf-Seed/f2#54]
**详细描述错误**
之前遇到的问题：
<details>
<summary>单击展开</summary>
 在使用函数 `f2 dy -c app.yaml --auto-cookie chrome` 的时候，
控制台提示 `tuple index out of range`。

我重装了 `f2` 这个项目在本地。
第一次时，使用函数 `f2 dy -c app.yaml --auto-cookie chrome` 函数很顺利。
可以在 `app.yaml` 文件中写入 `cookie`值。
当尝试运行程序时，例如：
`$ f2 dy -c f2/conf/app.yaml`

会提示 `tuple index out of range`。
程序无法实现下载功能。

在卸载所有依赖及 `f2` 后，重新使用 `pip install f2` 重新下载所有依赖及 `f2`。
程序执行成功。
函数 `f2 dy --init-config dy.yaml` 运行成功.。
使用函数 `f2 dy -c app.yaml --auto-cookie chrome` 更新cookie，
发生错误：
```
请前往QA文档 https://johnserf-seed.github.io/f2/question-answer/qa.html 查看相关帮助
ERROR    自动获取Cookie失败: tuple index out of range
自动获取Cookie失败: tuple index out of range
Aborted!
```
</details>

目前遇到的问题：
**配置文件路径不存在**

在使用`f2 -d DEBUG dy -c app.yaml -u https://xxx`后，提示错误：
`FileNotFound`
详细traceback请看

**系统平台**
<details>
<summary>单击展开</summary>
Q:你在哪个平台（Win/Linux/Mac）上运行？你使用的是什么浏览器？你使用的是什么终端软件？你使用的F2是什么版本？

A: 

 - 操作系统: [Windows 10 x64 22H2 19045.4046]
 - 浏览器 [Chrome 120.0.6099.110 (Official Build) (64-bit) (cohort: Stable Installs & Version Pins)]
 - 终端 [Windows Terminal 1.19.10573.0 + Git Bash 2.42.0.windows.2] 
 - F2版本 [0.0.1.4]

</details>

**错误重现**
之前遇到的问题：
<details>
<summary>单击展开</summary>
Q: 请你复制并粘贴出错时运行的命令和配置文件内容，以及重现该行为的步骤。如果你一次性就提供完整信息，就会节省很多解决问题的时间。

A: 

1.  使用命令 `f2 dy -c app.yaml --auto-cookie chrome` 后报错
2.  报错：
        INFO     App: douyin
        请前往QA文档 https://johnserf-seed.github.io/f2/question-answer/qa.html 查看相关帮助
        ERROR    自动获取Cookie失败: tuple index out of range
        自动获取Cookie失败: tuple index out of range
        Aborted
3. 无更多信息

Q: 请添加调试命令`f2 -d DEBUG`重新运行出错的命令并提供日志目录下的日志文件。

A: [2024-03-03-19-06-19.log](https://github.com/Johnserf-Seed/f2/files/14474482/2024-03-03-19-06-19.log)

</details>

目前遇到的问题：
<details>
<summary>单击展开</summary>
Q: 请你复制并粘贴出错时运行的命令和配置文件内容，以及重现该行为的步骤。如果你一次性就提供完整信息，就会节省很多解决问题的时间。

A: 

1.  使用命令 `f2 -d DEBUG -c app.yaml -u https://xxx` 后报错
2.  
![image](https://github.com/Johnserf-Seed/f2/assets/81968849/118a07cf-5c6d-45c9-9ebb-c9742bd90aba)

3. 
[app - Copy.txt](https://github.com/Johnserf-Seed/f2/files/14813717/app.-.Copy.txt)

Q: 请添加调试命令`f2 -d DEBUG`重新运行出错的命令并提供日志目录下的日志文件。

A: 
[2024-03-31-00-50-22.log](https://github.com/Johnserf-Seed/f2/files/14813721/2024-03-31-00-50-22.log)
其实这个log啥也没有。。但是在输出终端里有对应部分程序的报错。如上图

</details>

**预期行为**
之前的问题：
<details>
<summary>单击展开</summary>
程序自主在 `app.yaml` 中添加用户 cookie 及其他操作，
例如：
`f2 dy -c f2/conf/app.yaml`

</details>

现在的问题：
不应该出现错误啊？配置文件搁`f2\conf`里躺的好好的呢，不会找不到的啊？

**屏幕截图**
之前的问题：
<details>
<summary>单击展开</summary>
Windows Terminal:
![image](https://github.com/Johnserf-Seed/f2/assets/81968849/b7eaf712-81d6-41fb-b6db-d03aa7c150be)
![image](https://github.com/Johnserf-Seed/f2/assets/81968849/e41c4203-7f2f-4f30-865d-6d5345a4195c)

Git Bash:
![image](https://github.com/Johnserf-Seed/f2/assets/81968849/223dc492-c363-4c72-977a-72b937c02840)

</details>

现在的问题：
![image](https://github.com/Johnserf-Seed/f2/assets/81968849/7c9b8c09-998b-4120-bc10-86672fd6c3a1)
![image](https://github.com/Johnserf-Seed/f2/assets/81968849/f93999f9-bbdd-4b61-abad-50534f83d51d)
![image](https://github.com/Johnserf-Seed/f2/assets/81968849/ef6e9560-f2d7-42e2-aecf-0ecc508573ae)
![image](https://github.com/Johnserf-Seed/f2/assets/81968849/168f07b2-d406-44d3-8055-812c1f8eeca4)
![image](https://github.com/Johnserf-Seed/f2/assets/81968849/8c3296d8-5cca-453e-818f-fdbf9c3dbc10)

**其他**
之前的问题：
<details>
<summary>单击展开</summary>
在第一次安装后执行其他命令时也会报错。
但是程序提供了对应了log文件。
可惜重装之后并未解决，所以之前的log文件都被删除了。

</details>

**Comment by EsperantoP** [comment]
重装即可

**Comment by EsperantoP** [comment]
好吧。。这个问题还是避不开了

不知道是不是我应该在f2里面运行程序还是在windows任意的一个路径都可以运行f2啊 (╥_╥)

**Comment by EsperantoP** [comment]
或者说我的电脑坏掉了？(╥_╥)

**Comment by Johnserf-Seed** [comment]
你需要一个工作目录来存放配置文件和运行f2，如果你在桌面打开终端则需要保证桌面存在配置文件。

**Comment by EsperantoP** [comment]
> 你需要一个工作目录来存放配置文件和运行f2，如果你在桌面打开终端则需要保证桌面存在配置文件。

非常感谢！
(⁠≧⁠▽⁠≦⁠)
