### ISSUE TITLE
[QUESTION]请问0.0.1.4文件名模板不再支持{id}了吗？

### ISSUE THREAD

**Issue by cor961** [Johnserf-Seed/f2#55]
- [ ] ~~*在提问时请注意不要包含个人敏感信息*~~
- [ ] 我明白我的提问可能不会得到明确回复或解决。

**问题描述**
原来的TikTokTool，文件名模板我一直使用{create}_{id}_{desc}，现在使用f2报错：KeyError: "文件名模板字段 'id' 不存在，请检查"，在各种介绍和文档网站中均未找到说明是否f2仅支持{create}_{desc}模式。

**期望的支持**
请告知是否f2仅支持{create}_{desc}模式。

**Comment by Johnserf-Seed** [comment]
支持的改名了而已，uid和aweme_id。
