### ISSUE TITLE
[BUG]使用正确的cookie无法获取用户发布的视频信息

### ISSUE THREAD

**Issue by tongyan18** [Johnserf-Seed/f2#56]
- [ ] 我查看了 [文档](https://johnserf-seed.github.io/f2/quick-start.html) 以及 [已关闭的问题](https://github.com/Johnserf-Seed/f2/issues?q=is%3Aissue+is%3Aclosed) 以寻找可能的解决方案。
- [ ] 我在 [常见的问题与解决办法](https://johnserf-seed.github.io/f2/question-answer/qa.html) 中找不到我的问题。

**详细描述错误**
使用api的方式调用TiktokHandler(kwargs).fetch_user_post_videos方法时，使用正常登录并且可以正常使用的账号的cookie，无法获取到数据
![image](https://github.com/Johnserf-Seed/f2/assets/45142345/8e8bf645-936b-4b7a-83c6-2884797d4476)

![image](https://github.com/Johnserf-Seed/f2/assets/45142345/c44a513c-06f4-444f-b98b-439520292da1)

![image](https://github.com/Johnserf-Seed/f2/assets/45142345/b50084c1-6154-417a-8b5c-9e357eb08bab)
pyhton版本为3.11
linux和mac都有这种情况
存在某些cookie可以获取成功，但是大部分无法获取，麻烦老哥帮忙看下哈

**Comment by Johnserf-Seed** [comment]
响应为空都是cookie的问题，看文档的qa第一条

**Comment by tongyan18** [comment]
> 响应为空都是cookie的问题，看文档的qa第一条

现在发现一个现象，好像失败的cookie的账号都开通了tiktok小店，能成功的账号是没开通的，而且开通tk小店的账号请求官方接口会多返回一个字段
![image](https://github.com/Johnserf-Seed/f2/assets/45142345/79d1ab0e-c725-409d-9b32-2da92b4b705d)
cookie都是直接复制的请求头里面的，应该没问题呀，因为有些账号确实能获取成功

**Comment by Johnserf-Seed** [comment]
> > 响应为空都是cookie的问题，看文档的qa第一条
> 
> 现在发现一个现象，好像失败的cookie的账号都开通了tiktok小店，能成功的账号是没开通的，而且开通tk小店的账号请求官方接口会多返回一个字段
> ![image](https://github.com/Johnserf-Seed/f2/assets/45142345/79d1ab0e-c725-409d-9b32-2da92b4b705d)
> cookie都是直接复制的请求头里面的，应该没问题呀，因为有些账号确实能获取成功

我没有测试过是否和这个情况有关，你可以手动，多次的测试一个账号在网页中不同的cookie，另外你再提供一下完整代码片段我需要确定你的request请求部分

**Comment by tongyan18** [comment]
> > > 响应为空都是cookie的问题，看文档的qa第一条
> > 
> > 
> > 现在发现一个现象，好像失败的cookie的账号都开通了tiktok小店，能成功的账号是没开通的，而且开通tk小店的账号请求官方接口会多返回一个字段
> > ![image](https://private-user-images.githubusercontent.com/45142345/310090496-79d1ab0e-c725-409d-9b32-2da92b4b705d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzcxMDUsIm5iZiI6MTcwOTYzNjgwNSwicGF0aCI6Ii80NTE0MjM0NS8zMTAwOTA0OTYtNzlkMWFiMGUtYzcyNS00MDlkLTliMzItMmRhOTJiNGI3MDVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDExMDY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZmY0NGYwMGYxZjQ1M2E4NWM5ODdmMjMxMjYxMGZiMmIzZmNkNmU0YWMyZWU5MThkNWIwZDI3ZjViNDRmNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oQn3_m-mBakquoB2fujirCoYWXvaFT6UvxDhMD7KVSg)
> > cookie都是直接复制的请求头里面的，应该没问题呀，因为有些账号确实能获取成功
> 
> 我没有测试过是否和这个情况有关，你可以手动，多次的测试一个账号在网页中不同的cookie，另外你再提供一下完整代码片段我需要确定你的request请求部分

这是完整的方法了，我去试试同一个账号别的请求带的cookie
![image](https://github.com/Johnserf-Seed/f2/assets/45142345/2643a7aa-853c-45f2-95ac-58d7965a10fd)

**Comment by tongyan18** [comment]
老哥，在调用这个方法获取用户sec_uid的时候，我看会请求到用户首页比如https://www.tiktok.com/@danielleathena，但是这个请求返回的是一个Please wait的html，导致无法在html中解析到sec_uid，这个问题如何处理呀

**Comment by Johnserf-Seed** [comment]
> 老哥，在调用这个方法获取用户sec_uid的时候，我看会请求到用户首页比如[https://www.tiktok.com/@danielleathena，但是这个请求返回的是一个Please](https://www.tiktok.com/@danielleathena%EF%BC%8C%E4%BD%86%E6%98%AF%E8%BF%99%E4%B8%AA%E8%AF%B7%E6%B1%82%E8%BF%94%E5%9B%9E%E7%9A%84%E6%98%AF%E4%B8%80%E4%B8%AAPlease) wait的html，导致无法在html中解析到sec_uid，这个问题如何处理呀

那就是被风控弹验证码了，你用unique_id就行

**Comment by tongyan18** [comment]
> > 老哥，在调用这个方法获取用户sec_uid的时候，我看会请求到用户首页比如[https://www.tiktok.com/@danielleathena，但是这个请求返回的是一个Please](https://www.tiktok.com/@danielleathena%EF%BC%8C%E4%BD%86%E6%98%AF%E8%BF%99%E4%B8%AA%E8%AF%B7%E6%B1%82%E8%BF%94%E5%9B%9E%E7%9A%84%E6%98%AF%E4%B8%80%E4%B8%AAPlease) wait的html，导致无法在html中解析到sec_uid，这个问题如何处理呀
> 
> 那就是被风控弹验证码了，你用unique_id就行

但是这个方法是不是必须要sec_uid
![image](https://github.com/Johnserf-Seed/f2/assets/45142345/732a933d-dbf3-42e2-b8a9-eee1410b0fe5)

**Comment by Johnserf-Seed** [comment]
用`uniqueId`给`handler_user_profile`获取`secUid`曲线救国，获取用户数据的方法是支持2种id的
![image](https://github.com/Johnserf-Seed/f2/assets/40727745/aebc6ae8-be28-4d84-b91f-f7f99bf3a65c)

**Comment by tongyan18** [comment]
> 用`uniqueId`给`handler_user_profile`获取`secUid`曲线救国，获取用户数据的方法是支持2种id的 ![image](https://private-user-images.githubusercontent.com/40727745/310137299-aebc6ae8-be28-4d84-b91f-f7f99bf3a65c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDU3MDUsIm5iZiI6MTcwOTY0NTQwNSwicGF0aCI6Ii80MDcyNzc0NS8zMTAxMzcyOTktYWViYzZhZTgtYmUyOC00ZDg0LWI5MWYtZjdmOTliZjNhNjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEzMzAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MzEyNWFiZGYzMzk2ZDcxOWY0NWU0ZWVlYjhhNzQ0MzMxMzcyNDY1MDI1ZDU1MThjNDg5NDdmMTY4MzY5N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DXe_B2sI896PSAmMmcu0MteNg9jEbLpvO303zzYdetY)

获取用户接口返回值没有信息。。。。。。
{"extra":{"fatal_item_ids":[],"logid":"20240305133754F8BAED34B60F310D9AD0","now":1709645875000},"log_pb":{"impr_id":"20240305133754F8BAED34B60F310D9AD0"},"statusCode":10221,"status_code":0,"status_msg":"","userInfo":{}}

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/Johnserf-Seed/f2/assets/40727745/8a428a7c-61bf-46f4-8b2f-951e02e8e923)
你找的是这个用户吧，这不是可以么

**Comment by tongyan18** [comment]
> ![image](https://private-user-images.githubusercontent.com/40727745/310143152-8a428a7c-61bf-46f4-8b2f-951e02e8e923.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDY4ODQsIm5iZiI6MTcwOTY0NjU4NCwicGF0aCI6Ii80MDcyNzc0NS8zMTAxNDMxNTItOGE0MjhhN2MtNjFiZi00NmY0LThiMmYtOTUxZTAyZThlOTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEzNDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ODE4YjFiMmNmZGMzY2I1NjE1YWIyMWEyNDc2MDkyNDZkYzhkMWJhODNjYjYzMzJlN2JiNzUwODJhN2E3NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QL1vUUrFxZoVkbtik7LGkfgkcsK4qxOk4RrDwoyMHKs) 你找的是这个用户吧，这不是可以么

啊这。。这个方法不是就一个参数吗

> ![image](https://private-user-images.githubusercontent.com/40727745/310143152-8a428a7c-61bf-46f4-8b2f-951e02e8e923.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDY4ODQsIm5iZiI6MTcwOTY0NjU4NCwicGF0aCI6Ii80MDcyNzc0NS8zMTAxNDMxNTItOGE0MjhhN2MtNjFiZi00NmY0LThiMmYtOTUxZTAyZThlOTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEzNDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ODE4YjFiMmNmZGMzY2I1NjE1YWIyMWEyNDc2MDkyNDZkYzhkMWJhODNjYjYzMzJlN2JiNzUwODJhN2E3NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QL1vUUrFxZoVkbtik7LGkfgkcsK4qxOk4RrDwoyMHKs) 你找的是这个用户吧，这不是可以么

感谢老哥🙏，这样就能调通了
![image](https://github.com/Johnserf-Seed/f2/assets/45142345/0f257738-f233-4ccc-b015-4c4c1bdd7f6e)

**Comment by tongyan18** [comment]
> 那你可以打印看看你这个request的cookie看看够不够30个键，由于我不清楚你这个参数的上下文所以我不能给出准确判断。问题和账号类型应该是无关的。

大佬，这个问题能否让我提供你一个tk账号然后麻烦你验证下呢
