### ISSUE TITLE
可以获取用户主页数据吗 包括简介粉丝那些[QUESTION]

### ISSUE THREAD

**Issue by xiao0930** [Johnserf-Seed/f2#59]
- [ ] ~~*在提问时请注意不要包含个人敏感信息*~~
- [ ] 我明白我的提问可能不会得到明确回复或解决。

**问题描述**
简要描述你想要获取支持或询问的内容。

**其他细节**
提供任何相关的细节或背景信息，例如你要询问的函数或与项目相关的具体内容。

**截图/代码示例**
如果有必要，可以提供截图或代码示例以更好地说明问题或询问的内容。

**期望的支持**
简要说明你期望从社区或项目维护者那里得到的支持或回答。

**其他**
如果有其他需要补充的内容，请在此处添加。

**Comment by Johnserf-Seed** [comment]
可以，粉丝接口后续版本会更新
https://johnserf-seed.github.io/f2/guide/apps/douyin/#%E7%94%A8%E6%88%B7%E4%BF%A1%E6%81%AF-%F0%9F%9F%A2

**Comment by xiao0930** [comment]
请问tiktok也是差不多的用法吗&nbsp; 导入库就行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月17日(周日) 晚上9:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Johnserf-Seed/f2] 可以获取用户主页数据吗 包括简介粉丝那些[QUESTION] (Issue #59)




 
可以，粉丝接口后续版本会更新
 https://johnserf-seed.github.io/f2/guide/apps/douyin/#%E7%94%A8%E6%88%B7%E4%BF%A1%E6%81%AF-%F0%9F%9F%A2

**Comment by Johnserf-Seed** [comment]
> 请问tiktok也是差不多的用法吗&nbsp; 导入库就行
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月17日(周日) 晚上9:45 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Johnserf-Seed/f2] 可以获取用户主页数据吗 包括简介粉丝那些[QUESTION] (Issue #59) 可以，粉丝接口后续版本会更新 https://johnserf-seed.github.io/f2/guide/apps/douyin/#%E7%94%A8%E6%88%B7%E4%BF%A1%E6%81%AF-%F0%9F%9F%A2 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

是的
