### ISSUE TITLE
服务器上面爬取不到数据

### ISSUE THREAD

**Issue by getpu** [Johnserf-Seed/f2#61]
本地跑一切正常，上传到服务器状态一直是200 就是没数据

**Comment by qs-lll** [comment]
<img width="678" alt="image" src="https://github.com/Johnserf-Seed/f2/assets/5264241/5eac79a1-4303-46b6-887e-fc516f0ea118">

**Comment by qs-lll** [comment]
如果出现`WARNING  没有找到符合条件的作品`，请检查你是否配置了`interval`参数，该参数是用来设置作品发布时间的筛选条件。

解决办法：
1. 检查你的配置文件中是否有`interval`参数。如果没有，请添加为`interval: all`。
2. 如果你的配置文件中有`interval`参数，请检查你的`interval`参数是否设置正确。
3. `cli`命令中的`-i`参数也是用来设置作品发布时间的筛选条件 你可以设置为`-i all`。
4. 如果你使用了`-i`参数，请检查你的`-i`参数是否设置正确。

>

**Comment by getpu** [comment]
感谢，问题好像出在 Python 版本上面 ，我python版本用了 3.12 发现可以了
