### ISSUE TITLE
[BUG]设置interval之后有的时候找不到对应的作品

### ISSUE THREAD

**Issue by LRTFK** [Johnserf-Seed/f2#64]
设置interval之后有的时候找不到对应的作品
例如设置 interval为 2022-01-01|2023-01-01
在这个url运行就找不到作品
https://www.douyin.com/user/MS4wLjABAAAA6Y_2dEfQL7RUr6515qVJXINmruMWlL99pxhdMVjJfqs
设置 interval为 "all"就能找到。
log：
INFO     筛选日期区间：2022-01-01 00:00:00 至 2023-01-01 23:59:59
WARNING  作品发布时间不在指定区间内：2024-03-01 10-44-38
....
WARNING  没有找到符合条件的作品

**Comment by Johnserf-Seed** [comment]
emmm 你自己设置的22年到23年一年，24年的当然不属于了啊

**Comment by Johnserf-Seed** [comment]
![mmexport1711428461487.jpg](https://github.com/Johnserf-Seed/f2/assets/40727745/519d46bc-6eb4-46d1-b99c-a887c53854e7)

**Comment by LRTFK** [comment]
> emmm 你自己设置的22年到23年一年，24年的当然不属于了啊

我理解里面，设置interval为 2022-01-01|2023-01-01，就是搜索22年到23年这一年的作品。只要这个作者在22年到23年这一年期间有作品就应该能搜索到显示出来才对呀。
对上面那个作者，从22年到24年都有作品，我设置一个时间期间搜索不合理吗？

**Comment by junyaopk** [comment]
确实，设置时间范围后，我也搜索不到作品。

**Comment by Johnserf-Seed** [comment]
现已解决
