### ISSUE TITLE
安装完成后，运行应用的初始化配置文件命令报错

### ISSUE THREAD

**Issue by yifeiaaa** [Johnserf-Seed/f2#66]
运行 f2 apps --init-config my_apps.yaml命令时报错，ErrorMessage：“ No such command 'apps'.”
![微信图片_20240402150459](https://github.com/Johnserf-Seed/f2/assets/126935018/a6c34f84-c788-40bc-ab9f-730165422fc6)

**Comment by Johnserf-Seed** [comment]
你仔细看看有apps这个app吗

**Comment by yifeiaaa** [comment]
谢谢作者
