### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Angelagoodboy** [Johnserf-Seed/f2#74]
- [ 已检查] 我查看了 [文档](https://johnserf-seed.github.io/f2/quick-start.html) 以及 [已关闭的问题](https://github.com/Johnserf-Seed/f2/issues?q=is%3Aissue+is%3Aclosed) 以寻找可能的解决方案。
- [ 已检查] 我在 [常见的问题与解决办法](https://johnserf-seed.github.io/f2/question-answer/qa.html) 中找不到我的问题。
- [已检查 ] ~~*你的问题是公开的，请注意删除个人敏感内容再上传*~~
- [  已检查] 不按照模板填写的问题将不会得到优先的处理。

- 如果错误问题是可视化的，请在**屏幕截图**贴截图。如果你是开发者请在**错误重现**提供一个最小的代码示例来演示该问题。
- 相同的问题将会被标记`重复(duplicate)`，如果你的问题被标记为`已确认(confirmed)`则会在后续的推送中修复，请时刻留意。
- 退订邮件提醒请点击邮件的底部`unsubscribe`。

**详细描述错误**
简明扼要地描述遇到的错误。

**系统平台**
<details>
<summary>单击展开</summary>
Q:你在哪个平台（Win/Linux/Mac）上运行？你使用的是什么浏览器？你使用的是什么终端软件？你使用的F2是什么版本？

A: 

 - 操作系统: [macOs Catalina 10.15.7]
 - 浏览器 [echrome 123.0.6312.107]
 - 终端 [ 2.10] 
 - F2版本 [0.0.1.4]

</details>

**错误重现**
<details>
<summary>单击展开</summary>
Q: 请你复制并粘贴出错时运行的命令和配置文件内容，以及重现该行为的步骤。如果你一次性就提供完整信息，就会节省很多解决问题的时间。

A: 
1. f2 tk -M one -u  https://www.tiktok.com/@histoireduneflamme/video/7348889593413946657
2. 提示错误
<img width="1000" alt="image" src="https://github.com/Johnserf-Seed/f2/assets/55787363/3e8c5851-a6df-4eb8-93bb-e6403db41efa">
3. 配置文件
<img width="814" alt="image" src="https://github.com/Johnserf-Seed/f2/assets/55787363/d36b881d-1f09-4a1a-b35c-fbb92b6eec0e">

Q: 请添加调试命令`f2 -d DEBUG`重新运行出错的命令并提供日志目录下的日志文件。

A: 

Q: 如果是开发者请提供最小的代码示例

A: 

```python

```

</details>

**预期行为**
简明扼要地描述期望发生的事情。

**屏幕截图**
请添加截图以帮助解释你的问题。

**日志文件**
请添加调试日志文件以帮助解释你的问题。

**其他**
如有，可以添加有关问题的其他信息。

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/Johnserf-Seed/f2/assets/40727745/0950f3ff-4fd9-4b0d-8037-e4b86f9155eb)
https://johnserf-seed.github.io/f2/site-config.html#%E4%B8%BB%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6
