### ISSUE TITLE
抖音图文作品无法下载

### ISSUE THREAD

**Issue by yaochengfei** [Johnserf-Seed/f2#75]
作品链接：https://www.douyin.com/note/7350121602706689291
命令：f2 dy -M one -i all -d y -u https://www.douyin.com/note/7350121602706689291
请大佬帮忙查看下是什么原因导致的，谢谢
![QQ截图20240410141807](https://github.com/Johnserf-Seed/f2/assets/54323307/a1cce6ea-c3e9-4a12-8232-33e24690d52a)

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/Johnserf-Seed/f2/assets/40727745/21b8ffa6-3a94-405c-b8f6-98eedd571583)
一切z'c正常，如果你的cookie配置在主配置文件，请检查是否存在

**Comment by yaochengfei** [comment]
视频下载正常，就图片下载不行，在app.yaml里面有cookies的
![QQ截图20240410144422](https://github.com/Johnserf-Seed/f2/assets/54323307/b8dd31bf-3657-46b6-a655-136c479571b4)

**Comment by yaochengfei** [comment]
测试过，其他家的图文下载正常，就他家的下载报错，有点玄学了？

**Comment by Smecta** [comment]
可以正常下载实况作品吗？

**Comment by Johnserf-Seed** [comment]
> 可以正常下载实况作品吗？

可以，实况在抖音就是一个视频
![image](https://github.com/Johnserf-Seed/f2/assets/40727745/e7c08a7e-b567-484c-9aee-991c2138c365)

**Comment by Johnserf-Seed** [comment]
> > > 可以正常下载实况作品吗？
> > 
> > 
> > 可以，实况在抖音就是一个视频 ![image](https://private-user-images.githubusercontent.com/40727745/326482877-e7c08a7e-b567-484c-9aee-991c2138c365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzI5OTUsIm5iZiI6MTcxNTY3MjY5NSwicGF0aCI6Ii80MDcyNzc0NS8zMjY0ODI4NzctZTdjMDhhN2UtYjU2Ny00ODRjLTlhZWUtOTkxYzIxMzhjMzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA3NDQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMTE3NjVhM2UxZmFlMjJiOTVkNDc3ODNiZmJlOGRjZjA0YmUyMzc5MjVmZTEwNWJlNjg3NDViMjM2NzQzZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zJtZLVLBOTI4uI5SD2nqfjvlBd8W_eM7ibzGYNhWUGE)
> 
> 似乎作品多个实况的话会报错，返回ERROR 未在响应的地址中找到aweme_id，检查链接是否为作品页。

只有链接错误才会报这个错
