### ISSUE TITLE
[BUG]Tiktop的接口fetch_user_post_videos获取不到视频数据

### ISSUE THREAD

**Issue by kevin-lu** [Johnserf-Seed/f2#76]
Tiktop同一个cookie，能访问handler_user_profile、fetch_one_video，但是访问fetch_user_post_videos就一直重试提示“”响应内容为空, 状态码: 200“”，是因为/api/post/item_list/签名方式变了，尝试更换了很多cookie也是不行；
![image](https://github.com/Johnserf-Seed/f2/assets/8350699/8df607c7-fc93-43b0-bd30-4ecf4378752a)
![image](https://github.com/Johnserf-Seed/f2/assets/8350699/ee266202-1229-4fa8-9fdf-4019534afb21)

**Comment by Johnserf-Seed** [comment]
不是的，是风控，不要用美国代理。

**Comment by kevin-lu** [comment]
没有用代理 aws外国节点的服务器也会被风控的  大佬有什么推荐的吗
