### ISSUE TITLE
[BUG]抖音下载的视频文件大小错误，只有1KB

### ISSUE THREAD

**Issue by fuqianmeng** [Johnserf-Seed/f2#77]
如图
![屏幕截图 2024-04-10 224910](https://github.com/Johnserf-Seed/f2/assets/58690658/2d1f005e-43df-4a60-9f21-3a72e09af50e)
下载视频显示文件大小与实际下载文件大小不一致，f2还是会标记为完成。
测试图文下载正常；启用独立下载音频文件时，下载视频文件还是异常。
![屏幕截图 2024-04-10 230617](https://github.com/Johnserf-Seed/f2/assets/58690658/2bc26b2f-ed02-4494-ae6a-9bb3de890a17)

**Comment by Johnserf-Seed** [comment]
1. 文件比终端显示的偏小是正常的，终端里显示的是Content-Length的值，本地由系统计算得出的，编码不同大小也不同
2. 部分视频1kb为你本地的网络情况，这个在终端中也很清楚，所有的mp4并没有下载。因为没有加入完整性比较（接口会持续降画质）所以再你重新执行的时候跳过了这部分的下载。
![image](https://github.com/Johnserf-Seed/f2/assets/40727745/809014af-fd8b-475f-b876-0e7329a698d8)
![image](https://github.com/Johnserf-Seed/f2/assets/40727745/fe596550-5b0f-43c7-af3f-2756f3c4a1e7)
3. 新版本会将此种情况输出给用户，但无法改变这部分。
