### ISSUE TITLE
[BUG] tiktok下载  网络异常

### ISSUE THREAD

**Issue by dlswyk** [Johnserf-Seed/f2#78]
这个是我的自定义配置 
![2](https://github.com/Johnserf-Seed/f2/assets/48459921/fa44cb5e-ccae-42b8-8e8a-f8bea8e32a62)

错误信息
![1](https://github.com/Johnserf-Seed/f2/assets/48459921/de6b1ee6-dbe3-4515-b440-8a4e8bb7d6d6)

使用过 tiktok  的 cookie 测试过，也尝试过开启 vpn  进行下载

**Comment by wyk861417548** [comment]
抖音是正常的

**Comment by wyk861417548** [comment]
其他配置都没有动过，就新增了 抖音 和 tiktok 的自定义yaml 文件，  抖音是正常的

**Comment by Johnserf-Seed** [comment]
你需要配置代理，去`f2\conf\conf.yaml`配置

**Comment by wyk861417548** [comment]
怎么配置

**Comment by Johnserf-Seed** [comment]
> 怎么配置

填写代理服务器地址

**Comment by wyk861417548** [comment]
ok

**Comment by wyk861417548** [comment]
![3](https://github.com/Johnserf-Seed/f2/assets/48459921/67896541-0b70-4fd6-894b-dc9bb061621e)

tiktok 自动获取 cookie

**Comment by Johnserf-Seed** [comment]
> ![3](https://private-user-images.githubusercontent.com/48459921/321728168-67896541-0b70-4fd6-894b-dc9bb061621e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTc0MzYsIm5iZiI6MTcxMjg1NzEzNiwicGF0aCI6Ii80ODQ1OTkyMS8zMjE3MjgxNjgtNjc4OTY1NDEtMGI3MC00ZmQ2LTg5NGItZGM5YmIwNjE2MjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE3Mzg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYTVkOWZmNDJkOGI4ZjUzYjE4ZGRmNmQ3MWZmZDBmZGFkYzc2YjU1MDdiYzJmMWU0ZmZmOTNlOGQ5YTFmZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4oM4sxPLaDtLbJGJT-sXMIMW3DG80jGiW8nLBJe4SJw)
> 
> tiktok 自动获取 cookie

可以多测试几次，tk的风控最近比抖音还厉害，而且多半网页会弹验证码

**Comment by wyk861417548** [comment]
嗯  我自己网页找cookie 只有一次成功在下载状态  但是都是这种状态 
![4](https://github.com/Johnserf-Seed/f2/assets/48459921/48dffec2-1c19-471a-b83b-4446192c3558)

**Comment by Johnserf-Seed** [comment]
这个就是你代理问题了
