### ISSUE TITLE
[QUESTION] 下载提示有个字段不在数据库内 sqlite3.OperationalError:table user_info_web has no column named nickname_raw

### ISSUE THREAD

**Issue by Lzy0986** [Johnserf-Seed/f2#80]
作者主页：https://www.douyin.com/user/MS4wLjABAAAAAeOY-RiKPYuPMBKYVoTrIM18CnI1XdZJwiOrMaKQ_fJORDZ8LNrf_MiMqpbZcgPC
![Snipaste_2024-04-13_22-38-20](https://github.com/Johnserf-Seed/f2/assets/83565639/5d518aef-c5bc-4943-84b3-d6c4acd40acc)

**Comment by Lzy0986** [comment]
f2版本 0.0.1.5

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/issues/696#issuecomment-2051465629
