### ISSUE TITLE
可以下载单个视频，但是下载主页全部视频就会下载不全

### ISSUE THREAD

**Issue by ystu2024** [Johnserf-Seed/f2#81]
**问题描述**
下载单个视频没问题：
![image](https://github.com/Johnserf-Seed/f2/assets/163222720/b0c32e56-3f89-4e1c-a23f-016a0f5f5762)

下载主页的全部视频：
![image](https://github.com/Johnserf-Seed/f2/assets/163222720/929dc1f0-e58b-43a8-95a4-44616389a976)
会只下载几个视频，其他视频就下载不下来：
![image](https://github.com/Johnserf-Seed/f2/assets/163222720/c96ddd03-6d7d-429c-bdd2-6f97c33fdc69)

**期望的支持**
我想知道如何可以把主页的视频全部下载下来，谢谢

**Comment by ystu2024** [comment]
补充：
![image](https://github.com/Johnserf-Seed/f2/assets/163222720/aed28886-68c1-42ec-a7a1-d958bb58ba1d)

**Comment by dbnc** [comment]
![image](https://github.com/Johnserf-Seed/f2/assets/49666713/9c7cd676-f81b-4f9e-abb7-060210c7abee)
将最后一个值置空即可
