### ISSUE TITLE
能否做一个容器docker,这个安装linux 安装python3.11，会出现各种问题

### ISSUE THREAD

**Issue by talway** [Johnserf-Seed/f2#83]
在提出功能请求之前，请考虑在 https://github.com/Johnserf-Seed/f2/discussions 上发布反馈或在Discord中讨论。

**Q: 你有检查过类似建议的问题吗？**
在所有的问题列表里检查是否有类似的建议。
没有docker

**Q: 它能为你解决什么问题？**
该功能能解决你的什么问题？我也许可以建议一种现有的解决方法。
A: 计划安装到ubuntu20.04上面，查看系统3.8，所以需要升级，升级后，无法安装f2,各种报错；

希望打包好为docker,路径映射好，直接使用，
没必要为安装环境费时间，
谢谢

**Comment by Johnserf-Seed** [comment]
`F2`本身就是一个`python`的命令行工具，通过`pip`安装，无需制作`docker`镜像
