### ISSUE TITLE
各种错误求指导[QUESTION]

### ISSUE THREAD

**Issue by fungchunhoeasy** [Johnserf-Seed/f2#84]
PS C:\Users\Administrator> f2 dy -u https://v.douyin.com/iYvDJbHH/
INFO     App: douyin
INFO     主配置路径：C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\conf\app.yaml
INFO     自定义配置路径：C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\conf\app.ya
         ml
INFO     Version 0.0.1.5
ERROR    不存在该模式: None

**Comment by Johnserf-Seed** [comment]
配置文件按照文档里配置，你没有设置mode
