### ISSUE TITLE
ERROR    Error: No module named 'f2.apps.twitter'

### ISSUE THREAD

**Issue by 1300839062** [Johnserf-Seed/f2#85]
抖音视频配置conf后测试可以下载，apps选项使用wb、x、bili提示没有这些命令。如果要下载这些平台的数据，配置文件应该是怎样的。

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/Johnserf-Seed/f2/assets/40727745/aae53304-9841-40e0-b0ae-86835e57f037)

**Comment by Johnserf-Seed** [comment]
现已支持
