### ISSUE TITLE
WARNING  第 5 次响应内容为空, 状态码: 200

### ISSUE THREAD

**Issue by huazinet** [Johnserf-Seed/f2#88]
按照QA文档 https://johnserf-seed.github.io/f2/question-answer/qa.html 重新获取了cookie，但是还是为空，请问有啥解决的方案吗

**Comment by ahlblzk** [comment]
我这边最近也是这样了  正确获取了cookie好像也不能下载

**Comment by Johnserf-Seed** [comment]
> 我这边最近也是这样了 正确获取了cookie好像也不能下载

0.0.1.6将会开源新ab算法，可以解决现在旧xb接口陆续失效的问题

**Comment by GeLi1989** [comment]
> > 我这边最近也是这样了 正确获取了cookie好像也不能下载
> 
> 0.0.1.6将会开源新ab算法，可以解决现在旧xb接口陆续失效的问题

好像0.0.1.5版本的下载抖音视频不能用了。什么时候上线新版本？

**Comment by ccquan** [comment]
我也是，抖音平台的

**Comment by amibaren** [comment]
0.0.16的版本现在是否依然不能下载douyin的视频，前几个月还可以的，现在无论怎么调整配置cookie都提示响应内容为空 状态码200

**Comment by Johnserf-Seed** [comment]
> 0.0.16的版本现在是否依然不能下载douyin的视频，前几个月还可以的，现在无论怎么调整配置cookie都提示响应内容为空 状态码200

可以的
![image](https://github.com/user-attachments/assets/62dabb7b-ac73-44a8-a852-c46a49b5ed0a)
