### ISSUE TITLE
[QUESTION]自己点赞作品下载文件夹问题。

### ISSUE THREAD

**Issue by cor961** [Johnserf-Seed/f2#90]
- [ ] ~~*在提问时请注意不要包含个人敏感信息*~~
- [ ] 我明白我的提问可能不会得到明确回复或解决。

**问题描述**
目前，下载登陆以后的用户点赞的作品，文件夹路径是“\Download\douyin\like\登陆用户\”，所有点赞作品混到一起。

**期望的支持**
请问如何设置才能使点赞作品的文件夹路径变为“\Download\douyin\like\登陆用户\博主\”？

**Comment by Johnserf-Seed** [comment]
就这样设计的，点赞不支持按作品用户分类

**Comment by newdimitri** [comment]
> > 就这样设计的，点赞不支持按作品用户分类
> 
> 可以增加这样的功能吗？

你可以这样，在文件夹命名的时候，这样写：  naming: '{nickname}-{uid}-{desc}-{create}'
这样作者名字就在文件名最前面， 下载完成后，在资源管理器中按照文件名排序，相同作者的就会在一起了
