### ISSUE TITLE
名字是韩国字的，无法下载作品

### ISSUE THREAD

**Issue by poison998** [Johnserf-Seed/f2#91]
![image](https://github.com/Johnserf-Seed/f2/assets/124853945/9c9428a3-4b1d-4653-83d8-d369268e5b02)

**Comment by poison998** [comment]
下载到的名字会变成一个横岗

**Comment by Johnserf-Seed** [comment]
因为她的作品都是短剧，下个版本支持。

**Comment by poison998** [comment]
我查看了以下代码。 貌似是没有解析到下载地址  aweme_list

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/Johnserf-Seed/f2/assets/40727745/91024d49-4e14-471b-97d6-50355559bceb)
解析到了，只不过短剧的作品类型是201

**Comment by poison998** [comment]
好的， 我不确定，需要怎么解决这个问题

**Comment by Johnserf-Seed** [comment]
> 好的， 我不确定，需要怎么解决这个问题

你可以临时使用下面的方法，修改`f2/apps/douyin/dl.py`的`244`行代码，添加上短剧类型的`201`即可

原始
![image](https://github.com/Johnserf-Seed/f2/assets/40727745/8beaf8a1-d34d-43b7-8e93-b9b8f688e804)

修改为
![image](https://github.com/Johnserf-Seed/f2/assets/40727745/60fd5a38-db76-42eb-94d7-882b9621fce1)

**Comment by poison998** [comment]
谢谢
