### ISSUE TITLE
[QUESTION] 抖音合集无法下载的，

### ISSUE THREAD

**Issue by talway** [Johnserf-Seed/f2#94]
- [ ] ~~*在提问时请注意不要包含个人敏感信息*~~
- [ ] 我明白我的提问可能不会得到明确回复或解决。

**问题描述**
简要描述你想要获取支持或询问的内容。
地址
https://www.douyin.com/collection/7218227541453047867/1
我去除1
https://www.douyin.com/collection/7218227541453047867
无法下载，下载

**其他细节**
提供任何相关的细节或背景信息，例如你要询问的函数或与项目相关的具体内容。

**截图/代码示例**
如果有必要，可以提供截图或代码示例以更好地说明问题或询问的内容。

**期望的支持**
简要说明你期望从社区或项目维护者那里得到的支持或回答。

**其他**
如果有其他需要补充的内容，请在此处添加。

**Comment by shutdot** [comment]
是的，我也无法下载合集，无论设置什么url都不行。错误提示：AttributeError: 'PostDetailFilter' object has no attribute 'get'

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/Johnserf-Seed/f2/assets/40727745/7ab5ee83-f1c6-4c38-a7c9-042c0241ad3b)
请更新到`0.0.1.6`版本

**Comment by Johnserf-Seed** [comment]
> ![WX20240702-193131](https://private-user-images.githubusercontent.com/43690708/345004518-2c6315a9-fddd-4762-ac8f-cf4b7516e897.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MjA0NjIsIm5iZiI6MTcxOTkyMDE2MiwicGF0aCI6Ii80MzY5MDcwOC8zNDUwMDQ1MTgtMmM2MzE1YTktZmRkZC00NzYyLWFjOGYtY2Y0Yjc1MTZlODk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDExMzYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0YjM2YjBlOTkxN2VlYjMzOGMxYjVjY2RjZWY2MmE3YjY0MzU0NDY1MzliZTFjYTg4MmFjZTkyMDAwMzA4M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j5kVgRlLaPaduKE6yUhAq6WXgtZchNTpDxdkBpY5L3Q)
> 
> 报错没有了，但是提示--》 WARNING 没有找到符合条件的作品 https://www.douyin.com/collection/7270223014363400247 和 https://www.douyin.com/collection/7364201487259404325 这两个合集都不行。

https://johnserf-seed.github.io/f2/question-answer/qa.html#warning-%E6%B2%A1%E6%9C%89%E6%89%BE%E5%88%B0%E7%AC%A6%E5%90%88%E6%9D%A1%E4%BB%B6%E7%9A%84%E4%BD%9C%E5%93%81

**Comment by shutdot** [comment]
👍🐮，设置了interval，可以正常下载了，谢谢！

**Comment by talway** [comment]
> ![WX20240702-193131](https://private-user-images.githubusercontent.com/43690708/345004518-2c6315a9-fddd-4762-ac8f-cf4b7516e897.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNzIzMjgsIm5iZiI6MTcyMDE3MjAyOCwicGF0aCI6Ii80MzY5MDcwOC8zNDUwMDQ1MTgtMmM2MzE1YTktZmRkZC00NzYyLWFjOGYtY2Y0Yjc1MTZlODk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA5MzM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYTRhNDFlMjE0MzUyMTNhNzZkZDdmNmJjMzUwNWNkZTExMzc0NDRlMDdhZGQ0OWVmYTNmNDA4OTlkMmM1MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DfH-LF76NtLA6xph0_4VM5CrwzMu9dKiiMRiRh2id2c)
> 
> 报错没有了，但是提示--》 WARNING 没有找到符合条件的作品 https://www.douyin.com/collection/7270223014363400247 和 https://www.douyin.com/collection/7364201487259404325 这两个合集都不行。

能否把这个参数，设置默认all,我看好多都这个问题，初始化没有这个参数，基本都要踩坑
 -i --interval

**Comment by Johnserf-Seed** [comment]
初始化配置时interval已设置默认值
