### ISSUE TITLE
[QUESTION]TIKTOK的链接不可访问

### ISSUE THREAD

**Issue by Usagiu** [Johnserf-Seed/f2#95]
fetch_one_video之后的链接无法打开

**Comment by Johnserf-Seed** [comment]
正常，代理问题，你用浏览器也打不开

**Comment by Usagiu** [comment]
> 正常，代理问题，你用浏览器也打不开

同一个视频tiktok的网页链接可以打开, 但是接口返回的无法打开

**Comment by Johnserf-Seed** [comment]
查阅最新文档QA https://f2.wiki/question-answer/qa#tiktok-403-forbidden
